// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.corbado.passkeys_android;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.CLASS;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class Messages {
  static boolean pigeonDoubleEquals(double a, double b) {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (a == 0.0 ? 0.0 : a) == (b == 0.0 ? 0.0 : b) || (Double.isNaN(a) && Double.isNaN(b));
  }

  static boolean pigeonFloatEquals(float a, float b) {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (a == 0.0f ? 0.0f : a) == (b == 0.0f ? 0.0f : b) || (Float.isNaN(a) && Float.isNaN(b));
  }

  static int pigeonDoubleHashCode(double d) {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    if (d == 0.0) {
      d = 0.0;
    }
    long bits = Double.doubleToLongBits(d);
    return (int) (bits ^ (bits >>> 32));
  }

  static int pigeonFloatHashCode(float f) {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    if (f == 0.0f) {
      f = 0.0f;
    }
    return Float.floatToIntBits(f);
  }

  static boolean pigeonDeepEquals(Object a, Object b) {
    if (a == b) { return true; }
    if (a == null || b == null) { return false; }
    if (a instanceof byte[] && b instanceof byte[]) {
      return Arrays.equals((byte[]) a, (byte[]) b);
    }
    if (a instanceof int[] && b instanceof int[]) {
      return Arrays.equals((int[]) a, (int[]) b);
    }
    if (a instanceof long[] && b instanceof long[]) {
      return Arrays.equals((long[]) a, (long[]) b);
    }
    if (a instanceof double[] && b instanceof double[]) {
      double[] da = (double[]) a;
      double[] db = (double[]) b;
      if (da.length != db.length) {
        return false;
      }
      for (int i = 0; i < da.length; i++) {
        if (!pigeonDoubleEquals(da[i], db[i])) {
          return false;
        }
      }
      return true;
    }
    if (a instanceof List && b instanceof List) {
      List<?> listA = (List<?>) a;
      List<?> listB = (List<?>) b;
      if (listA.size() != listB.size()) { return false; }
      for (int i = 0; i < listA.size(); i++) {
        if (!pigeonDeepEquals(listA.get(i), listB.get(i))) {
          return false;
        }
      }
      return true;
    }
    if (a instanceof Map && b instanceof Map) {
      Map<?, ?> mapA = (Map<?, ?>) a;
      Map<?, ?> mapB = (Map<?, ?>) b;
      if (mapA.size() != mapB.size()) { return false; }
      for (Map.Entry<?, ?> entryA : mapA.entrySet()) {
        Object keyA = entryA.getKey();
        Object valueA = entryA.getValue();
        boolean found = false;
        for (Map.Entry<?, ?> entryB : mapB.entrySet()) {
          Object keyB = entryB.getKey();
          if (pigeonDeepEquals(keyA, keyB)) {
            Object valueB = entryB.getValue();
            if (pigeonDeepEquals(valueA, valueB)) {
              found = true;
              break;
            } else {
              return false;
            }
          }
        }
        if (!found) {
          return false;
        }
      }
      return true;
    }
    if (a instanceof Double && b instanceof Double) {
      return pigeonDoubleEquals((double) a, (double) b);
    }
    if (a instanceof Float && b instanceof Float) {
      return pigeonFloatEquals((float) a, (float) b);
    }
    return a.equals(b);
  }

  static int pigeonDeepHashCode(Object value) {
    if (value == null) { return 0; }
    if (value instanceof byte[]) {
      return Arrays.hashCode((byte[]) value);
    }
    if (value instanceof int[]) {
      return Arrays.hashCode((int[]) value);
    }
    if (value instanceof long[]) {
      return Arrays.hashCode((long[]) value);
    }
    if (value instanceof double[]) {
      double[] da = (double[]) value;
      int result = 1;
      for (double d : da) {
        result = 31 * result + pigeonDoubleHashCode(d);
      }
      return result;
    }
    if (value instanceof List) {
      int result = 1;
      for (Object item : (List<?>) value) {
        result = 31 * result + pigeonDeepHashCode(item);
      }
      return result;
    }
    if (value instanceof Map) {
      int result = 0;
      for (Map.Entry<?, ?> entry : ((Map<?, ?>) value).entrySet()) {
        result += ((pigeonDeepHashCode(entry.getKey()) * 31) ^ pigeonDeepHashCode(entry.getValue()));
      }
      return result;
    }
    if (value instanceof Object[]) {
      int result = 1;
      for (Object item : (Object[]) value) {
        result = 31 * result + pigeonDeepHashCode(item);
      }
      return result;
    }
    if (value instanceof Double) {
      return pigeonDoubleHashCode((double) value);
    }
    if (value instanceof Float) {
      return pigeonFloatHashCode((float) value);
    }
    return value.hashCode();
  }


  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  @Target(METHOD)
  @Retention(CLASS)
  @interface CanIgnoreReturnValue {}

  /**
   * Represents a relying party
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class RelyingParty {
    /** Name of the relying party */
    private @NonNull String name;

    public @NonNull String getName() {
      return name;
    }

    public void setName(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"name\" is null.");
      }
      this.name = setterArg;
    }

    /** ID of the relying party */
    private @NonNull String id;

    public @NonNull String getId() {
      return id;
    }

    public void setId(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"id\" is null.");
      }
      this.id = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    RelyingParty() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      RelyingParty that = (RelyingParty) o;
      return pigeonDeepEquals(name, that.name) && pigeonDeepEquals(id, that.id);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), name, id};
      return pigeonDeepHashCode(fields);
    }

    public static final class Builder {

      private @Nullable String name;

      @CanIgnoreReturnValue
      public @NonNull Builder setName(@NonNull String setterArg) {
        this.name = setterArg;
        return this;
      }

      private @Nullable String id;

      @CanIgnoreReturnValue
      public @NonNull Builder setId(@NonNull String setterArg) {
        this.id = setterArg;
        return this;
      }

      public @NonNull RelyingParty build() {
        RelyingParty pigeonReturn = new RelyingParty();
        pigeonReturn.setName(name);
        pigeonReturn.setId(id);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(2);
      toListResult.add(name);
      toListResult.add(id);
      return toListResult;
    }

    static @NonNull RelyingParty fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      RelyingParty pigeonResult = new RelyingParty();
      Object name = pigeonVar_list.get(0);
      pigeonResult.setName((String) name);
      Object id = pigeonVar_list.get(1);
      pigeonResult.setId((String) id);
      return pigeonResult;
    }
  }

  /**
   * Represents a public key credential parameter
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class PubKeyCredParam {
    /** The type */
    private @NonNull String type;

    public @NonNull String getType() {
      return type;
    }

    public void setType(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"type\" is null.");
      }
      this.type = setterArg;
    }

    /** The algorithm */
    private @NonNull Long alg;

    public @NonNull Long getAlg() {
      return alg;
    }

    public void setAlg(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"alg\" is null.");
      }
      this.alg = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    PubKeyCredParam() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      PubKeyCredParam that = (PubKeyCredParam) o;
      return pigeonDeepEquals(type, that.type) && pigeonDeepEquals(alg, that.alg);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), type, alg};
      return pigeonDeepHashCode(fields);
    }

    public static final class Builder {

      private @Nullable String type;

      @CanIgnoreReturnValue
      public @NonNull Builder setType(@NonNull String setterArg) {
        this.type = setterArg;
        return this;
      }

      private @Nullable Long alg;

      @CanIgnoreReturnValue
      public @NonNull Builder setAlg(@NonNull Long setterArg) {
        this.alg = setterArg;
        return this;
      }

      public @NonNull PubKeyCredParam build() {
        PubKeyCredParam pigeonReturn = new PubKeyCredParam();
        pigeonReturn.setType(type);
        pigeonReturn.setAlg(alg);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(2);
      toListResult.add(type);
      toListResult.add(alg);
      return toListResult;
    }

    static @NonNull PubKeyCredParam fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      PubKeyCredParam pigeonResult = new PubKeyCredParam();
      Object type = pigeonVar_list.get(0);
      pigeonResult.setType((String) type);
      Object alg = pigeonVar_list.get(1);
      pigeonResult.setAlg((Long) alg);
      return pigeonResult;
    }
  }

  /**
   * Represents a user
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class User {
    /** The display name */
    private @NonNull String displayName;

    public @NonNull String getDisplayName() {
      return displayName;
    }

    public void setDisplayName(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"displayName\" is null.");
      }
      this.displayName = setterArg;
    }

    /** The name */
    private @NonNull String name;

    public @NonNull String getName() {
      return name;
    }

    public void setName(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"name\" is null.");
      }
      this.name = setterArg;
    }

    /** The ID */
    private @NonNull String id;

    public @NonNull String getId() {
      return id;
    }

    public void setId(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"id\" is null.");
      }
      this.id = setterArg;
    }

    /** The icon */
    private @Nullable String icon;

    public @Nullable String getIcon() {
      return icon;
    }

    public void setIcon(@Nullable String setterArg) {
      this.icon = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    User() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      User that = (User) o;
      return pigeonDeepEquals(displayName, that.displayName) && pigeonDeepEquals(name, that.name) && pigeonDeepEquals(id, that.id) && pigeonDeepEquals(icon, that.icon);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), displayName, name, id, icon};
      return pigeonDeepHashCode(fields);
    }

    public static final class Builder {

      private @Nullable String displayName;

      @CanIgnoreReturnValue
      public @NonNull Builder setDisplayName(@NonNull String setterArg) {
        this.displayName = setterArg;
        return this;
      }

      private @Nullable String name;

      @CanIgnoreReturnValue
      public @NonNull Builder setName(@NonNull String setterArg) {
        this.name = setterArg;
        return this;
      }

      private @Nullable String id;

      @CanIgnoreReturnValue
      public @NonNull Builder setId(@NonNull String setterArg) {
        this.id = setterArg;
        return this;
      }

      private @Nullable String icon;

      @CanIgnoreReturnValue
      public @NonNull Builder setIcon(@Nullable String setterArg) {
        this.icon = setterArg;
        return this;
      }

      public @NonNull User build() {
        User pigeonReturn = new User();
        pigeonReturn.setDisplayName(displayName);
        pigeonReturn.setName(name);
        pigeonReturn.setId(id);
        pigeonReturn.setIcon(icon);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(4);
      toListResult.add(displayName);
      toListResult.add(name);
      toListResult.add(id);
      toListResult.add(icon);
      return toListResult;
    }

    static @NonNull User fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      User pigeonResult = new User();
      Object displayName = pigeonVar_list.get(0);
      pigeonResult.setDisplayName((String) displayName);
      Object name = pigeonVar_list.get(1);
      pigeonResult.setName((String) name);
      Object id = pigeonVar_list.get(2);
      pigeonResult.setId((String) id);
      Object icon = pigeonVar_list.get(3);
      pigeonResult.setIcon((String) icon);
      return pigeonResult;
    }
  }

  /**
   * Represents an allowed credential
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class AllowCredential {
    /** The type */
    private @NonNull String type;

    public @NonNull String getType() {
      return type;
    }

    public void setType(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"type\" is null.");
      }
      this.type = setterArg;
    }

    /** The ID */
    private @NonNull String id;

    public @NonNull String getId() {
      return id;
    }

    public void setId(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"id\" is null.");
      }
      this.id = setterArg;
    }

    /** The transports */
    private @NonNull List<String> transports;

    public @NonNull List<String> getTransports() {
      return transports;
    }

    public void setTransports(@NonNull List<String> setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"transports\" is null.");
      }
      this.transports = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    AllowCredential() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      AllowCredential that = (AllowCredential) o;
      return pigeonDeepEquals(type, that.type) && pigeonDeepEquals(id, that.id) && pigeonDeepEquals(transports, that.transports);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), type, id, transports};
      return pigeonDeepHashCode(fields);
    }

    public static final class Builder {

      private @Nullable String type;

      @CanIgnoreReturnValue
      public @NonNull Builder setType(@NonNull String setterArg) {
        this.type = setterArg;
        return this;
      }

      private @Nullable String id;

      @CanIgnoreReturnValue
      public @NonNull Builder setId(@NonNull String setterArg) {
        this.id = setterArg;
        return this;
      }

      private @Nullable List<String> transports;

      @CanIgnoreReturnValue
      public @NonNull Builder setTransports(@NonNull List<String> setterArg) {
        this.transports = setterArg;
        return this;
      }

      public @NonNull AllowCredential build() {
        AllowCredential pigeonReturn = new AllowCredential();
        pigeonReturn.setType(type);
        pigeonReturn.setId(id);
        pigeonReturn.setTransports(transports);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(3);
      toListResult.add(type);
      toListResult.add(id);
      toListResult.add(transports);
      return toListResult;
    }

    static @NonNull AllowCredential fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      AllowCredential pigeonResult = new AllowCredential();
      Object type = pigeonVar_list.get(0);
      pigeonResult.setType((String) type);
      Object id = pigeonVar_list.get(1);
      pigeonResult.setId((String) id);
      Object transports = pigeonVar_list.get(2);
      pigeonResult.setTransports((List<String>) transports);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class ExcludeCredential {
    /** The type */
    private @NonNull String type;

    public @NonNull String getType() {
      return type;
    }

    public void setType(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"type\" is null.");
      }
      this.type = setterArg;
    }

    /** The ID */
    private @NonNull String id;

    public @NonNull String getId() {
      return id;
    }

    public void setId(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"id\" is null.");
      }
      this.id = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    ExcludeCredential() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      ExcludeCredential that = (ExcludeCredential) o;
      return pigeonDeepEquals(type, that.type) && pigeonDeepEquals(id, that.id);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), type, id};
      return pigeonDeepHashCode(fields);
    }

    public static final class Builder {

      private @Nullable String type;

      @CanIgnoreReturnValue
      public @NonNull Builder setType(@NonNull String setterArg) {
        this.type = setterArg;
        return this;
      }

      private @Nullable String id;

      @CanIgnoreReturnValue
      public @NonNull Builder setId(@NonNull String setterArg) {
        this.id = setterArg;
        return this;
      }

      public @NonNull ExcludeCredential build() {
        ExcludeCredential pigeonReturn = new ExcludeCredential();
        pigeonReturn.setType(type);
        pigeonReturn.setId(id);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(2);
      toListResult.add(type);
      toListResult.add(id);
      return toListResult;
    }

    static @NonNull ExcludeCredential fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      ExcludeCredential pigeonResult = new ExcludeCredential();
      Object type = pigeonVar_list.get(0);
      pigeonResult.setType((String) type);
      Object id = pigeonVar_list.get(1);
      pigeonResult.setId((String) id);
      return pigeonResult;
    }
  }

  /**
   * Represents an authenticator selection
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class AuthenticatorSelection {
    /** The authenticator attachment */
    private @Nullable String authenticatorAttachment;

    public @Nullable String getAuthenticatorAttachment() {
      return authenticatorAttachment;
    }

    public void setAuthenticatorAttachment(@Nullable String setterArg) {
      this.authenticatorAttachment = setterArg;
    }

    /** Whether a resident key is required */
    private @NonNull Boolean requireResidentKey;

    public @NonNull Boolean getRequireResidentKey() {
      return requireResidentKey;
    }

    public void setRequireResidentKey(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"requireResidentKey\" is null.");
      }
      this.requireResidentKey = setterArg;
    }

    /** The resident key */
    private @NonNull String residentKey;

    public @NonNull String getResidentKey() {
      return residentKey;
    }

    public void setResidentKey(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"residentKey\" is null.");
      }
      this.residentKey = setterArg;
    }

    /** The user verification */
    private @NonNull String userVerification;

    public @NonNull String getUserVerification() {
      return userVerification;
    }

    public void setUserVerification(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"userVerification\" is null.");
      }
      this.userVerification = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    AuthenticatorSelection() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      AuthenticatorSelection that = (AuthenticatorSelection) o;
      return pigeonDeepEquals(authenticatorAttachment, that.authenticatorAttachment) && pigeonDeepEquals(requireResidentKey, that.requireResidentKey) && pigeonDeepEquals(residentKey, that.residentKey) && pigeonDeepEquals(userVerification, that.userVerification);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), authenticatorAttachment, requireResidentKey, residentKey, userVerification};
      return pigeonDeepHashCode(fields);
    }

    public static final class Builder {

      private @Nullable String authenticatorAttachment;

      @CanIgnoreReturnValue
      public @NonNull Builder setAuthenticatorAttachment(@Nullable String setterArg) {
        this.authenticatorAttachment = setterArg;
        return this;
      }

      private @Nullable Boolean requireResidentKey;

      @CanIgnoreReturnValue
      public @NonNull Builder setRequireResidentKey(@NonNull Boolean setterArg) {
        this.requireResidentKey = setterArg;
        return this;
      }

      private @Nullable String residentKey;

      @CanIgnoreReturnValue
      public @NonNull Builder setResidentKey(@NonNull String setterArg) {
        this.residentKey = setterArg;
        return this;
      }

      private @Nullable String userVerification;

      @CanIgnoreReturnValue
      public @NonNull Builder setUserVerification(@NonNull String setterArg) {
        this.userVerification = setterArg;
        return this;
      }

      public @NonNull AuthenticatorSelection build() {
        AuthenticatorSelection pigeonReturn = new AuthenticatorSelection();
        pigeonReturn.setAuthenticatorAttachment(authenticatorAttachment);
        pigeonReturn.setRequireResidentKey(requireResidentKey);
        pigeonReturn.setResidentKey(residentKey);
        pigeonReturn.setUserVerification(userVerification);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(4);
      toListResult.add(authenticatorAttachment);
      toListResult.add(requireResidentKey);
      toListResult.add(residentKey);
      toListResult.add(userVerification);
      return toListResult;
    }

    static @NonNull AuthenticatorSelection fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      AuthenticatorSelection pigeonResult = new AuthenticatorSelection();
      Object authenticatorAttachment = pigeonVar_list.get(0);
      pigeonResult.setAuthenticatorAttachment((String) authenticatorAttachment);
      Object requireResidentKey = pigeonVar_list.get(1);
      pigeonResult.setRequireResidentKey((Boolean) requireResidentKey);
      Object residentKey = pigeonVar_list.get(2);
      pigeonResult.setResidentKey((String) residentKey);
      Object userVerification = pigeonVar_list.get(3);
      pigeonResult.setUserVerification((String) userVerification);
      return pigeonResult;
    }
  }

  /**
   * Represents a register response
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class RegisterResponse {
    /** The ID */
    private @NonNull String id;

    public @NonNull String getId() {
      return id;
    }

    public void setId(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"id\" is null.");
      }
      this.id = setterArg;
    }

    /** The raw ID */
    private @NonNull String rawId;

    public @NonNull String getRawId() {
      return rawId;
    }

    public void setRawId(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"rawId\" is null.");
      }
      this.rawId = setterArg;
    }

    /** The client data JSON */
    private @NonNull String clientDataJSON;

    public @NonNull String getClientDataJSON() {
      return clientDataJSON;
    }

    public void setClientDataJSON(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"clientDataJSON\" is null.");
      }
      this.clientDataJSON = setterArg;
    }

    /** The attestation object */
    private @NonNull String attestationObject;

    public @NonNull String getAttestationObject() {
      return attestationObject;
    }

    public void setAttestationObject(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"attestationObject\" is null.");
      }
      this.attestationObject = setterArg;
    }

    /** The supported transports for the authenticator */
    private @NonNull List<String> transports;

    public @NonNull List<String> getTransports() {
      return transports;
    }

    public void setTransports(@NonNull List<String> setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"transports\" is null.");
      }
      this.transports = setterArg;
    }

    /** The clientExtensionResults - PRF results */
    private @Nullable Map<String, Object> clientExtensionResults;

    public @Nullable Map<String, Object> getClientExtensionResults() {
      return clientExtensionResults;
    }

    public void setClientExtensionResults(@Nullable Map<String, Object> setterArg) {
      this.clientExtensionResults = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    RegisterResponse() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      RegisterResponse that = (RegisterResponse) o;
      return pigeonDeepEquals(id, that.id) && pigeonDeepEquals(rawId, that.rawId) && pigeonDeepEquals(clientDataJSON, that.clientDataJSON) && pigeonDeepEquals(attestationObject, that.attestationObject) && pigeonDeepEquals(transports, that.transports) && pigeonDeepEquals(clientExtensionResults, that.clientExtensionResults);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), id, rawId, clientDataJSON, attestationObject, transports, clientExtensionResults};
      return pigeonDeepHashCode(fields);
    }

    public static final class Builder {

      private @Nullable String id;

      @CanIgnoreReturnValue
      public @NonNull Builder setId(@NonNull String setterArg) {
        this.id = setterArg;
        return this;
      }

      private @Nullable String rawId;

      @CanIgnoreReturnValue
      public @NonNull Builder setRawId(@NonNull String setterArg) {
        this.rawId = setterArg;
        return this;
      }

      private @Nullable String clientDataJSON;

      @CanIgnoreReturnValue
      public @NonNull Builder setClientDataJSON(@NonNull String setterArg) {
        this.clientDataJSON = setterArg;
        return this;
      }

      private @Nullable String attestationObject;

      @CanIgnoreReturnValue
      public @NonNull Builder setAttestationObject(@NonNull String setterArg) {
        this.attestationObject = setterArg;
        return this;
      }

      private @Nullable List<String> transports;

      @CanIgnoreReturnValue
      public @NonNull Builder setTransports(@NonNull List<String> setterArg) {
        this.transports = setterArg;
        return this;
      }

      private @Nullable Map<String, Object> clientExtensionResults;

      @CanIgnoreReturnValue
      public @NonNull Builder setClientExtensionResults(@Nullable Map<String, Object> setterArg) {
        this.clientExtensionResults = setterArg;
        return this;
      }

      public @NonNull RegisterResponse build() {
        RegisterResponse pigeonReturn = new RegisterResponse();
        pigeonReturn.setId(id);
        pigeonReturn.setRawId(rawId);
        pigeonReturn.setClientDataJSON(clientDataJSON);
        pigeonReturn.setAttestationObject(attestationObject);
        pigeonReturn.setTransports(transports);
        pigeonReturn.setClientExtensionResults(clientExtensionResults);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(6);
      toListResult.add(id);
      toListResult.add(rawId);
      toListResult.add(clientDataJSON);
      toListResult.add(attestationObject);
      toListResult.add(transports);
      toListResult.add(clientExtensionResults);
      return toListResult;
    }

    static @NonNull RegisterResponse fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      RegisterResponse pigeonResult = new RegisterResponse();
      Object id = pigeonVar_list.get(0);
      pigeonResult.setId((String) id);
      Object rawId = pigeonVar_list.get(1);
      pigeonResult.setRawId((String) rawId);
      Object clientDataJSON = pigeonVar_list.get(2);
      pigeonResult.setClientDataJSON((String) clientDataJSON);
      Object attestationObject = pigeonVar_list.get(3);
      pigeonResult.setAttestationObject((String) attestationObject);
      Object transports = pigeonVar_list.get(4);
      pigeonResult.setTransports((List<String>) transports);
      Object clientExtensionResults = pigeonVar_list.get(5);
      pigeonResult.setClientExtensionResults((Map<String, Object>) clientExtensionResults);
      return pigeonResult;
    }
  }

  /**
   * Represents an authenticate response
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class AuthenticateResponse {
    /** The ID */
    private @NonNull String id;

    public @NonNull String getId() {
      return id;
    }

    public void setId(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"id\" is null.");
      }
      this.id = setterArg;
    }

    /** The raw ID */
    private @NonNull String rawId;

    public @NonNull String getRawId() {
      return rawId;
    }

    public void setRawId(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"rawId\" is null.");
      }
      this.rawId = setterArg;
    }

    /** The client data JSON */
    private @NonNull String clientDataJSON;

    public @NonNull String getClientDataJSON() {
      return clientDataJSON;
    }

    public void setClientDataJSON(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"clientDataJSON\" is null.");
      }
      this.clientDataJSON = setterArg;
    }

    /** The authenticator data */
    private @NonNull String authenticatorData;

    public @NonNull String getAuthenticatorData() {
      return authenticatorData;
    }

    public void setAuthenticatorData(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"authenticatorData\" is null.");
      }
      this.authenticatorData = setterArg;
    }

    /** The signature */
    private @NonNull String signature;

    public @NonNull String getSignature() {
      return signature;
    }

    public void setSignature(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"signature\" is null.");
      }
      this.signature = setterArg;
    }

    /** The userHandle */
    private @NonNull String userHandle;

    public @NonNull String getUserHandle() {
      return userHandle;
    }

    public void setUserHandle(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"userHandle\" is null.");
      }
      this.userHandle = setterArg;
    }

    /** The clientExtensionResults - PRF results */
    private @Nullable Map<String, Object> clientExtensionResults;

    public @Nullable Map<String, Object> getClientExtensionResults() {
      return clientExtensionResults;
    }

    public void setClientExtensionResults(@Nullable Map<String, Object> setterArg) {
      this.clientExtensionResults = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    AuthenticateResponse() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      AuthenticateResponse that = (AuthenticateResponse) o;
      return pigeonDeepEquals(id, that.id) && pigeonDeepEquals(rawId, that.rawId) && pigeonDeepEquals(clientDataJSON, that.clientDataJSON) && pigeonDeepEquals(authenticatorData, that.authenticatorData) && pigeonDeepEquals(signature, that.signature) && pigeonDeepEquals(userHandle, that.userHandle) && pigeonDeepEquals(clientExtensionResults, that.clientExtensionResults);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), id, rawId, clientDataJSON, authenticatorData, signature, userHandle, clientExtensionResults};
      return pigeonDeepHashCode(fields);
    }

    public static final class Builder {

      private @Nullable String id;

      @CanIgnoreReturnValue
      public @NonNull Builder setId(@NonNull String setterArg) {
        this.id = setterArg;
        return this;
      }

      private @Nullable String rawId;

      @CanIgnoreReturnValue
      public @NonNull Builder setRawId(@NonNull String setterArg) {
        this.rawId = setterArg;
        return this;
      }

      private @Nullable String clientDataJSON;

      @CanIgnoreReturnValue
      public @NonNull Builder setClientDataJSON(@NonNull String setterArg) {
        this.clientDataJSON = setterArg;
        return this;
      }

      private @Nullable String authenticatorData;

      @CanIgnoreReturnValue
      public @NonNull Builder setAuthenticatorData(@NonNull String setterArg) {
        this.authenticatorData = setterArg;
        return this;
      }

      private @Nullable String signature;

      @CanIgnoreReturnValue
      public @NonNull Builder setSignature(@NonNull String setterArg) {
        this.signature = setterArg;
        return this;
      }

      private @Nullable String userHandle;

      @CanIgnoreReturnValue
      public @NonNull Builder setUserHandle(@NonNull String setterArg) {
        this.userHandle = setterArg;
        return this;
      }

      private @Nullable Map<String, Object> clientExtensionResults;

      @CanIgnoreReturnValue
      public @NonNull Builder setClientExtensionResults(@Nullable Map<String, Object> setterArg) {
        this.clientExtensionResults = setterArg;
        return this;
      }

      public @NonNull AuthenticateResponse build() {
        AuthenticateResponse pigeonReturn = new AuthenticateResponse();
        pigeonReturn.setId(id);
        pigeonReturn.setRawId(rawId);
        pigeonReturn.setClientDataJSON(clientDataJSON);
        pigeonReturn.setAuthenticatorData(authenticatorData);
        pigeonReturn.setSignature(signature);
        pigeonReturn.setUserHandle(userHandle);
        pigeonReturn.setClientExtensionResults(clientExtensionResults);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(7);
      toListResult.add(id);
      toListResult.add(rawId);
      toListResult.add(clientDataJSON);
      toListResult.add(authenticatorData);
      toListResult.add(signature);
      toListResult.add(userHandle);
      toListResult.add(clientExtensionResults);
      return toListResult;
    }

    static @NonNull AuthenticateResponse fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      AuthenticateResponse pigeonResult = new AuthenticateResponse();
      Object id = pigeonVar_list.get(0);
      pigeonResult.setId((String) id);
      Object rawId = pigeonVar_list.get(1);
      pigeonResult.setRawId((String) rawId);
      Object clientDataJSON = pigeonVar_list.get(2);
      pigeonResult.setClientDataJSON((String) clientDataJSON);
      Object authenticatorData = pigeonVar_list.get(3);
      pigeonResult.setAuthenticatorData((String) authenticatorData);
      Object signature = pigeonVar_list.get(4);
      pigeonResult.setSignature((String) signature);
      Object userHandle = pigeonVar_list.get(5);
      pigeonResult.setUserHandle((String) userHandle);
      Object clientExtensionResults = pigeonVar_list.get(6);
      pigeonResult.setClientExtensionResults((Map<String, Object>) clientExtensionResults);
      return pigeonResult;
    }
  }

  private static class PigeonCodec extends StandardMessageCodec {
    public static final PigeonCodec INSTANCE = new PigeonCodec();

    private PigeonCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 129:
          return RelyingParty.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 130:
          return PubKeyCredParam.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 131:
          return User.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 132:
          return AllowCredential.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 133:
          return ExcludeCredential.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 134:
          return AuthenticatorSelection.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 135:
          return RegisterResponse.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 136:
          return AuthenticateResponse.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof RelyingParty) {
        stream.write(129);
        writeValue(stream, ((RelyingParty) value).toList());
      } else if (value instanceof PubKeyCredParam) {
        stream.write(130);
        writeValue(stream, ((PubKeyCredParam) value).toList());
      } else if (value instanceof User) {
        stream.write(131);
        writeValue(stream, ((User) value).toList());
      } else if (value instanceof AllowCredential) {
        stream.write(132);
        writeValue(stream, ((AllowCredential) value).toList());
      } else if (value instanceof ExcludeCredential) {
        stream.write(133);
        writeValue(stream, ((ExcludeCredential) value).toList());
      } else if (value instanceof AuthenticatorSelection) {
        stream.write(134);
        writeValue(stream, ((AuthenticatorSelection) value).toList());
      } else if (value instanceof RegisterResponse) {
        stream.write(135);
        writeValue(stream, ((RegisterResponse) value).toList());
      } else if (value instanceof AuthenticateResponse) {
        stream.write(136);
        writeValue(stream, ((AuthenticateResponse) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }


  /** Asynchronous error handling return type for non-nullable API method returns. */
  public interface Result<T> {
    /** Success case callback method for handling returns. */
    void success(@NonNull T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for nullable API method returns. */
  public interface NullableResult<T> {
    /** Success case callback method for handling returns. */
    void success(@Nullable T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for void API method returns. */
  public interface VoidResult {
    /** Success case callback method for handling returns. */
    void success();

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface PasskeysApi {

    void canAuthenticate(@NonNull Result<Boolean> result);

    void hasPasskeySupport(@NonNull Result<Boolean> result);

    void register(@NonNull String challenge, @NonNull RelyingParty relyingParty, @NonNull User user, @Nullable AuthenticatorSelection authenticatorSelection, @Nullable List<PubKeyCredParam> pubKeyCredParams, @Nullable Long timeout, @Nullable String attestation, @NonNull List<ExcludeCredential> excludeCredentials, @Nullable String salt, @NonNull Result<RegisterResponse> result);

    void authenticate(@NonNull String relyingPartyId, @NonNull String challenge, @Nullable Long timeout, @Nullable String userVerification, @Nullable List<AllowCredential> allowCredentials, @Nullable Boolean preferImmediatelyAvailableCredentials, @Nullable String salt, @NonNull Result<AuthenticateResponse> result);

    void cancelCurrentAuthenticatorOperation(@NonNull VoidResult result);

    void signalUnknownCredential(@NonNull String relyingPartyId, @NonNull String credentialId, @NonNull VoidResult result);

    void signalAllAcceptedCredentials(@NonNull String relyingPartyId, @NonNull String userId, @NonNull List<String> allAcceptedCredentialIds, @NonNull VoidResult result);

    /** The codec used by PasskeysApi. */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    /**Sets up an instance of `PasskeysApi` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable PasskeysApi api) {
      setUp(binaryMessenger, "", api);
    }
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @NonNull String messageChannelSuffix, @Nullable PasskeysApi api) {
      messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.passkeys_android.PasskeysApi.canAuthenticate" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                Result<Boolean> resultCallback =
                    new Result<Boolean>() {
                      public void success(Boolean result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.canAuthenticate(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.passkeys_android.PasskeysApi.hasPasskeySupport" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                Result<Boolean> resultCallback =
                    new Result<Boolean>() {
                      public void success(Boolean result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.hasPasskeySupport(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.passkeys_android.PasskeysApi.register" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                String challengeArg = (String) args.get(0);
                RelyingParty relyingPartyArg = (RelyingParty) args.get(1);
                User userArg = (User) args.get(2);
                AuthenticatorSelection authenticatorSelectionArg = (AuthenticatorSelection) args.get(3);
                List<PubKeyCredParam> pubKeyCredParamsArg = (List<PubKeyCredParam>) args.get(4);
                Long timeoutArg = (Long) args.get(5);
                String attestationArg = (String) args.get(6);
                List<ExcludeCredential> excludeCredentialsArg = (List<ExcludeCredential>) args.get(7);
                String saltArg = (String) args.get(8);
                Result<RegisterResponse> resultCallback =
                    new Result<RegisterResponse>() {
                      public void success(RegisterResponse result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.register(challengeArg, relyingPartyArg, userArg, authenticatorSelectionArg, pubKeyCredParamsArg, timeoutArg, attestationArg, excludeCredentialsArg, saltArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.passkeys_android.PasskeysApi.authenticate" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                String relyingPartyIdArg = (String) args.get(0);
                String challengeArg = (String) args.get(1);
                Long timeoutArg = (Long) args.get(2);
                String userVerificationArg = (String) args.get(3);
                List<AllowCredential> allowCredentialsArg = (List<AllowCredential>) args.get(4);
                Boolean preferImmediatelyAvailableCredentialsArg = (Boolean) args.get(5);
                String saltArg = (String) args.get(6);
                Result<AuthenticateResponse> resultCallback =
                    new Result<AuthenticateResponse>() {
                      public void success(AuthenticateResponse result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.authenticate(relyingPartyIdArg, challengeArg, timeoutArg, userVerificationArg, allowCredentialsArg, preferImmediatelyAvailableCredentialsArg, saltArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.passkeys_android.PasskeysApi.cancelCurrentAuthenticatorOperation" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                VoidResult resultCallback =
                    new VoidResult() {
                      public void success() {
                        wrapped.add(0, null);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.cancelCurrentAuthenticatorOperation(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.passkeys_android.PasskeysApi.signalUnknownCredential" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                String relyingPartyIdArg = (String) args.get(0);
                String credentialIdArg = (String) args.get(1);
                VoidResult resultCallback =
                    new VoidResult() {
                      public void success() {
                        wrapped.add(0, null);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.signalUnknownCredential(relyingPartyIdArg, credentialIdArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.passkeys_android.PasskeysApi.signalAllAcceptedCredentials" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                String relyingPartyIdArg = (String) args.get(0);
                String userIdArg = (String) args.get(1);
                List<String> allAcceptedCredentialIdsArg = (List<String>) args.get(2);
                VoidResult resultCallback =
                    new VoidResult() {
                      public void success() {
                        wrapped.add(0, null);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.signalAllAcceptedCredentials(relyingPartyIdArg, userIdArg, allAcceptedCredentialIdsArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
}
