// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsmessages(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashmessages(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsmessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsmessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsmessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsmessages(lhsKey, rhsKey) {
          if deepEqualsmessages(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsmessages(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashmessages(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashmessages(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashmessages(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashmessages(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashmessages(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashmessages(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Represents a relying party
///
/// Generated class from Pigeon that represents data sent in messages.
struct RelyingParty: Hashable {
  /// Name of the relying party
  var name: String
  /// ID of the relying party
  var id: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RelyingParty? {
    let name = pigeonVar_list[0] as! String
    let id = pigeonVar_list[1] as! String

    return RelyingParty(
      name: name,
      id: id
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      id,
    ]
  }
  static func == (lhs: RelyingParty, rhs: RelyingParty) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsmessages(lhs.name, rhs.name) && deepEqualsmessages(lhs.id, rhs.id)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RelyingParty")
    deepHashmessages(value: name, hasher: &hasher)
    deepHashmessages(value: id, hasher: &hasher)
  }
}

/// Represents a credential
///
/// Generated class from Pigeon that represents data sent in messages.
struct CredentialType: Hashable {
  /// The type of the credential.
  var type: String
  /// The ID of the credential.
  var id: String
  /// The transports of the credential.
  var transports: [String?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CredentialType? {
    let type = pigeonVar_list[0] as! String
    let id = pigeonVar_list[1] as! String
    let transports = pigeonVar_list[2] as! [String?]

    return CredentialType(
      type: type,
      id: id,
      transports: transports
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      id,
      transports,
    ]
  }
  static func == (lhs: CredentialType, rhs: CredentialType) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsmessages(lhs.type, rhs.type) && deepEqualsmessages(lhs.id, rhs.id) && deepEqualsmessages(lhs.transports, rhs.transports)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CredentialType")
    deepHashmessages(value: type, hasher: &hasher)
    deepHashmessages(value: id, hasher: &hasher)
    deepHashmessages(value: transports, hasher: &hasher)
  }
}

/// Represents a user
///
/// Generated class from Pigeon that represents data sent in messages.
struct User: Hashable {
  /// The name
  var name: String
  /// The ID
  var id: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> User? {
    let name = pigeonVar_list[0] as! String
    let id = pigeonVar_list[1] as! String

    return User(
      name: name,
      id: id
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      id,
    ]
  }
  static func == (lhs: User, rhs: User) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsmessages(lhs.name, rhs.name) && deepEqualsmessages(lhs.id, rhs.id)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("User")
    deepHashmessages(value: name, hasher: &hasher)
    deepHashmessages(value: id, hasher: &hasher)
  }
}

/// Represents a register response
///
/// Generated class from Pigeon that represents data sent in messages.
struct RegisterResponse: Hashable {
  /// The ID
  var id: String
  /// The raw ID
  var rawId: String
  /// The client data JSON
  var clientDataJSON: String
  /// The attestation object
  var attestationObject: String
  /// The supported transports for the authenticator
  var transports: [String?]
  /// The clientExtensionResults - PRF results
  var clientExtensionResults: [String?: Any?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RegisterResponse? {
    let id = pigeonVar_list[0] as! String
    let rawId = pigeonVar_list[1] as! String
    let clientDataJSON = pigeonVar_list[2] as! String
    let attestationObject = pigeonVar_list[3] as! String
    let transports = pigeonVar_list[4] as! [String?]
    let clientExtensionResults: [String?: Any?]? = nilOrValue(pigeonVar_list[5])

    return RegisterResponse(
      id: id,
      rawId: rawId,
      clientDataJSON: clientDataJSON,
      attestationObject: attestationObject,
      transports: transports,
      clientExtensionResults: clientExtensionResults
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      rawId,
      clientDataJSON,
      attestationObject,
      transports,
      clientExtensionResults,
    ]
  }
  static func == (lhs: RegisterResponse, rhs: RegisterResponse) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsmessages(lhs.id, rhs.id) && deepEqualsmessages(lhs.rawId, rhs.rawId) && deepEqualsmessages(lhs.clientDataJSON, rhs.clientDataJSON) && deepEqualsmessages(lhs.attestationObject, rhs.attestationObject) && deepEqualsmessages(lhs.transports, rhs.transports) && deepEqualsmessages(lhs.clientExtensionResults, rhs.clientExtensionResults)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RegisterResponse")
    deepHashmessages(value: id, hasher: &hasher)
    deepHashmessages(value: rawId, hasher: &hasher)
    deepHashmessages(value: clientDataJSON, hasher: &hasher)
    deepHashmessages(value: attestationObject, hasher: &hasher)
    deepHashmessages(value: transports, hasher: &hasher)
    deepHashmessages(value: clientExtensionResults, hasher: &hasher)
  }
}

/// Represents an authenticate response
///
/// Generated class from Pigeon that represents data sent in messages.
struct AuthenticateResponse: Hashable {
  /// The ID
  var id: String
  /// The raw ID
  var rawId: String
  /// The client data JSON
  var clientDataJSON: String
  /// The authenticator data
  var authenticatorData: String
  /// Signed challenge
  var signature: String
  var userHandle: String? = nil
  /// The clientExtensionResults - PRF results
  var clientExtensionResults: [String?: Any?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AuthenticateResponse? {
    let id = pigeonVar_list[0] as! String
    let rawId = pigeonVar_list[1] as! String
    let clientDataJSON = pigeonVar_list[2] as! String
    let authenticatorData = pigeonVar_list[3] as! String
    let signature = pigeonVar_list[4] as! String
    let userHandle: String? = nilOrValue(pigeonVar_list[5])
    let clientExtensionResults: [String?: Any?]? = nilOrValue(pigeonVar_list[6])

    return AuthenticateResponse(
      id: id,
      rawId: rawId,
      clientDataJSON: clientDataJSON,
      authenticatorData: authenticatorData,
      signature: signature,
      userHandle: userHandle,
      clientExtensionResults: clientExtensionResults
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      rawId,
      clientDataJSON,
      authenticatorData,
      signature,
      userHandle,
      clientExtensionResults,
    ]
  }
  static func == (lhs: AuthenticateResponse, rhs: AuthenticateResponse) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsmessages(lhs.id, rhs.id) && deepEqualsmessages(lhs.rawId, rhs.rawId) && deepEqualsmessages(lhs.clientDataJSON, rhs.clientDataJSON) && deepEqualsmessages(lhs.authenticatorData, rhs.authenticatorData) && deepEqualsmessages(lhs.signature, rhs.signature) && deepEqualsmessages(lhs.userHandle, rhs.userHandle) && deepEqualsmessages(lhs.clientExtensionResults, rhs.clientExtensionResults)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AuthenticateResponse")
    deepHashmessages(value: id, hasher: &hasher)
    deepHashmessages(value: rawId, hasher: &hasher)
    deepHashmessages(value: clientDataJSON, hasher: &hasher)
    deepHashmessages(value: authenticatorData, hasher: &hasher)
    deepHashmessages(value: signature, hasher: &hasher)
    deepHashmessages(value: userHandle, hasher: &hasher)
    deepHashmessages(value: clientExtensionResults, hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return RelyingParty.fromList(self.readValue() as! [Any?])
    case 130:
      return CredentialType.fromList(self.readValue() as! [Any?])
    case 131:
      return User.fromList(self.readValue() as! [Any?])
    case 132:
      return RegisterResponse.fromList(self.readValue() as! [Any?])
    case 133:
      return AuthenticateResponse.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? RelyingParty {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? CredentialType {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? User {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? RegisterResponse {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? AuthenticateResponse {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PasskeysApi {
  func canAuthenticate() throws -> Bool
  func hasBiometrics() throws -> Bool
  func register(challenge: String, relyingParty: RelyingParty, user: User, excludeCredentials: [CredentialType], pubKeyCredValues: [Int64], canBePlatformAuthenticator: Bool, canBeSecurityKey: Bool, residentKeyPreference: String?, attestationPreference: String?, salt: String?, completion: @escaping (Result<RegisterResponse, Error>) -> Void)
  func authenticate(relyingPartyId: String, challenge: String, conditionalUI: Bool, allowedCredentials: [CredentialType], preferImmediatelyAvailableCredentials: Bool, salt: String?, completion: @escaping (Result<AuthenticateResponse, Error>) -> Void)
  func cancelCurrentAuthenticatorOperation(completion: @escaping (Result<Void, Error>) -> Void)
  func signalUnknownCredential(relyingPartyId: String, credentialId: String, completion: @escaping (Result<Void, Error>) -> Void)
  func signalAllAcceptedCredentials(relyingPartyId: String, userId: String, allAcceptedCredentialIds: [String], completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PasskeysApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `PasskeysApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PasskeysApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let canAuthenticateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.passkeys_darwin.PasskeysApi.canAuthenticate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      canAuthenticateChannel.setMessageHandler { _, reply in
        do {
          let result = try api.canAuthenticate()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      canAuthenticateChannel.setMessageHandler(nil)
    }
    let hasBiometricsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.passkeys_darwin.PasskeysApi.hasBiometrics\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      hasBiometricsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.hasBiometrics()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      hasBiometricsChannel.setMessageHandler(nil)
    }
    let registerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.passkeys_darwin.PasskeysApi.register\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      registerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let challengeArg = args[0] as! String
        let relyingPartyArg = args[1] as! RelyingParty
        let userArg = args[2] as! User
        let excludeCredentialsArg = args[3] as! [CredentialType]
        let pubKeyCredValuesArg = args[4] as! [Int64]
        let canBePlatformAuthenticatorArg = args[5] as! Bool
        let canBeSecurityKeyArg = args[6] as! Bool
        let residentKeyPreferenceArg: String? = nilOrValue(args[7])
        let attestationPreferenceArg: String? = nilOrValue(args[8])
        let saltArg: String? = nilOrValue(args[9])
        api.register(challenge: challengeArg, relyingParty: relyingPartyArg, user: userArg, excludeCredentials: excludeCredentialsArg, pubKeyCredValues: pubKeyCredValuesArg, canBePlatformAuthenticator: canBePlatformAuthenticatorArg, canBeSecurityKey: canBeSecurityKeyArg, residentKeyPreference: residentKeyPreferenceArg, attestationPreference: attestationPreferenceArg, salt: saltArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      registerChannel.setMessageHandler(nil)
    }
    let authenticateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.passkeys_darwin.PasskeysApi.authenticate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      authenticateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let relyingPartyIdArg = args[0] as! String
        let challengeArg = args[1] as! String
        let conditionalUIArg = args[2] as! Bool
        let allowedCredentialsArg = args[3] as! [CredentialType]
        let preferImmediatelyAvailableCredentialsArg = args[4] as! Bool
        let saltArg: String? = nilOrValue(args[5])
        api.authenticate(relyingPartyId: relyingPartyIdArg, challenge: challengeArg, conditionalUI: conditionalUIArg, allowedCredentials: allowedCredentialsArg, preferImmediatelyAvailableCredentials: preferImmediatelyAvailableCredentialsArg, salt: saltArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      authenticateChannel.setMessageHandler(nil)
    }
    let cancelCurrentAuthenticatorOperationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.passkeys_darwin.PasskeysApi.cancelCurrentAuthenticatorOperation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelCurrentAuthenticatorOperationChannel.setMessageHandler { _, reply in
        api.cancelCurrentAuthenticatorOperation { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelCurrentAuthenticatorOperationChannel.setMessageHandler(nil)
    }
    let signalUnknownCredentialChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.passkeys_darwin.PasskeysApi.signalUnknownCredential\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      signalUnknownCredentialChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let relyingPartyIdArg = args[0] as! String
        let credentialIdArg = args[1] as! String
        api.signalUnknownCredential(relyingPartyId: relyingPartyIdArg, credentialId: credentialIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      signalUnknownCredentialChannel.setMessageHandler(nil)
    }
    let signalAllAcceptedCredentialsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.passkeys_darwin.PasskeysApi.signalAllAcceptedCredentials\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      signalAllAcceptedCredentialsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let relyingPartyIdArg = args[0] as! String
        let userIdArg = args[1] as! String
        let allAcceptedCredentialIdsArg = args[2] as! [String]
        api.signalAllAcceptedCredentials(relyingPartyId: relyingPartyIdArg, userId: userIdArg, allAcceptedCredentialIds: allAcceptedCredentialIdsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      signalAllAcceptedCredentialsChannel.setMessageHandler(nil)
    }
  }
}
