name: corbado_auth_example
description: Example code that shows how to use corbado_auth
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  corbado_auth:
    path: ../
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  go_router: ^10.1.2
  json_editor: ^0.0.8
  url_launcher: ^6.2.1
  riverpod: ^2.3.10
  flutter_riverpod: ^2.3.10
  hooks_riverpod: ^2.4.0
  overlay_support: ^2.1.0
  corbado_telemetry_api_client: ^1.0.2

dev_dependencies:
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true