// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "messages.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <cmath>
#include <limits>
#include <map>
#include <optional>
#include <string>

namespace passkeys_windows {
using ::flutter::BasicMessageChannel;
using ::flutter::CustomEncodableValue;
using ::flutter::EncodableList;
using ::flutter::EncodableMap;
using ::flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

namespace {
template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b);

bool PigeonInternalDeepEquals(const double& a, const double& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b);

template<typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b);

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b);

template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b) {
  return a == b;
}

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b) {
  if (a.size() != b.size()) {
    return false;
  }
  for (size_t i = 0; i < a.size(); ++i) {
    if (!PigeonInternalDeepEquals(a[i], b[i])) {
      return false;
    }
  }
  return true;
}

template <typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b) {
  if (a.size() != b.size()) {
    return false;
  }
  for (const auto& kv : a) {
    bool found = false;
    for (const auto& b_kv : b) {
      if (PigeonInternalDeepEquals(kv.first, b_kv.first)) {
        if (PigeonInternalDeepEquals(kv.second, b_kv.second)) {
          found = true;
          break;
        } else {
          return false;
        }
      }
    }
    if (!found) {
      return false;
    }
  }
  return true;
}

bool PigeonInternalDeepEquals(const double& a, const double& b) {
  // Normalize -0.0 to 0.0 and handle NaN equality.
  return (a == b) || (std::isnan(a) && std::isnan(b));
}

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b) {
  if (!a && !b) {
    return true;
  }
  if (!a || !b) {
    return false;
  }
  return PigeonInternalDeepEquals(*a, *b);
}

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b) {
  if (a.get() == b.get()) {
    return true;
  }
  if (!a || !b) {
    return false;
  }
  return PigeonInternalDeepEquals(*a, *b);
}

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b) {
  if (a.index() != b.index()) {
    return false;
  }
  if (const double* da = std::get_if<double>(&a)) {
    return PigeonInternalDeepEquals(*da, std::get<double>(b));
  } else if (const ::flutter::EncodableList* la = std::get_if<::flutter::EncodableList>(&a)) {
    return PigeonInternalDeepEquals(*la, std::get<::flutter::EncodableList>(b));
  } else if (const ::flutter::EncodableMap* ma = std::get_if<::flutter::EncodableMap>(&a)) {
    return PigeonInternalDeepEquals(*ma, std::get<::flutter::EncodableMap>(b));
  }
  return a == b;
}

template <typename T>
size_t PigeonInternalDeepHash(const T& v);

size_t PigeonInternalDeepHash(const double& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v);

template <typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v);

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v);

template <typename T>
size_t PigeonInternalDeepHash(const T& v) {
  return std::hash<T>()(v);
}

template <typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v) {
  size_t result = 1;
  for (const auto& item : v) {
    result = result * 31 + PigeonInternalDeepHash(item);
  }
  return result;
}

template <typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v) {
  size_t result = 0;
  for (const auto& kv : v) {
    result += ((PigeonInternalDeepHash(kv.first) * 31) ^ PigeonInternalDeepHash(kv.second));
  }
  return result;
}

size_t PigeonInternalDeepHash(const double& v) {
  if (std::isnan(v)) {
    // Normalize NaN to a consistent hash.
    return std::hash<double>()(std::numeric_limits<double>::quiet_NaN());
  }
  if (v == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return std::hash<double>()(0.0);
  }
  return std::hash<double>()(v);
}

template <typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v) {
  return v ? PigeonInternalDeepHash(*v) : 0;
}

template <typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v) {
  return v ? PigeonInternalDeepHash(*v) : 0;
}

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v) {
  size_t result = v.index();
  if (const double* dv = std::get_if<double>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*dv);
  } else if (const ::flutter::EncodableList* lv =
                 std::get_if<::flutter::EncodableList>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*lv);
  } else if (const ::flutter::EncodableMap* mv =
                 std::get_if<::flutter::EncodableMap>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*mv);
  } else {
    std::visit(
        [&result](const auto& val) {
          using T = std::decay_t<decltype(val)>;
          if constexpr (!std::is_same_v<T, double> &&
                        !std::is_same_v<T, ::flutter::EncodableList> &&
                        !std::is_same_v<T, ::flutter::EncodableMap> &&
                        !std::is_same_v<T, std::monostate> &&
                        !std::is_same_v<T, ::flutter::CustomEncodableValue>) {
            result = result * 31 + PigeonInternalDeepHash(val);
          }
        },
        v);
  }
  return result;
}

}  // namespace
// RelyingParty

RelyingParty::RelyingParty(
  const std::string& name,
  const std::string& id)
 : name_(name),
    id_(id) {}

const std::string& RelyingParty::name() const {
  return name_;
}

void RelyingParty::set_name(std::string_view value_arg) {
  name_ = value_arg;
}


const std::string& RelyingParty::id() const {
  return id_;
}

void RelyingParty::set_id(std::string_view value_arg) {
  id_ = value_arg;
}


EncodableList RelyingParty::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(EncodableValue(name_));
  list.push_back(EncodableValue(id_));
  return list;
}

RelyingParty RelyingParty::FromEncodableList(const EncodableList& list) {
  RelyingParty decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]));
  return decoded;
}

bool RelyingParty::operator==(const RelyingParty& other) const {
  return PigeonInternalDeepEquals(name_, other.name_) && PigeonInternalDeepEquals(id_, other.id_);
}

bool RelyingParty::operator!=(const RelyingParty& other) const {
  return !(*this == other);
}

size_t RelyingParty::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(name_);
  result = result * 31 + PigeonInternalDeepHash(id_);
  return result;
}

size_t PigeonInternalDeepHash(const RelyingParty& v) {
  return v.Hash();
}

// PubKeyCredParam

PubKeyCredParam::PubKeyCredParam(
  const std::string& type,
  int64_t alg)
 : type_(type),
    alg_(alg) {}

const std::string& PubKeyCredParam::type() const {
  return type_;
}

void PubKeyCredParam::set_type(std::string_view value_arg) {
  type_ = value_arg;
}


int64_t PubKeyCredParam::alg() const {
  return alg_;
}

void PubKeyCredParam::set_alg(int64_t value_arg) {
  alg_ = value_arg;
}


EncodableList PubKeyCredParam::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(EncodableValue(type_));
  list.push_back(EncodableValue(alg_));
  return list;
}

PubKeyCredParam PubKeyCredParam::FromEncodableList(const EncodableList& list) {
  PubKeyCredParam decoded(
    std::get<std::string>(list[0]),
    std::get<int64_t>(list[1]));
  return decoded;
}

bool PubKeyCredParam::operator==(const PubKeyCredParam& other) const {
  return PigeonInternalDeepEquals(type_, other.type_) && PigeonInternalDeepEquals(alg_, other.alg_);
}

bool PubKeyCredParam::operator!=(const PubKeyCredParam& other) const {
  return !(*this == other);
}

size_t PubKeyCredParam::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(type_);
  result = result * 31 + PigeonInternalDeepHash(alg_);
  return result;
}

size_t PigeonInternalDeepHash(const PubKeyCredParam& v) {
  return v.Hash();
}

// User

User::User(
  const std::string& display_name,
  const std::string& name,
  const std::string& id)
 : display_name_(display_name),
    name_(name),
    id_(id) {}

User::User(
  const std::string& display_name,
  const std::string& name,
  const std::string& id,
  const std::string* icon)
 : display_name_(display_name),
    name_(name),
    id_(id),
    icon_(icon ? std::optional<std::string>(*icon) : std::nullopt) {}

const std::string& User::display_name() const {
  return display_name_;
}

void User::set_display_name(std::string_view value_arg) {
  display_name_ = value_arg;
}


const std::string& User::name() const {
  return name_;
}

void User::set_name(std::string_view value_arg) {
  name_ = value_arg;
}


const std::string& User::id() const {
  return id_;
}

void User::set_id(std::string_view value_arg) {
  id_ = value_arg;
}


const std::string* User::icon() const {
  return icon_ ? &(*icon_) : nullptr;
}

void User::set_icon(const std::string_view* value_arg) {
  icon_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void User::set_icon(std::string_view value_arg) {
  icon_ = value_arg;
}


EncodableList User::ToEncodableList() const {
  EncodableList list;
  list.reserve(4);
  list.push_back(EncodableValue(display_name_));
  list.push_back(EncodableValue(name_));
  list.push_back(EncodableValue(id_));
  list.push_back(icon_ ? EncodableValue(*icon_) : EncodableValue());
  return list;
}

User User::FromEncodableList(const EncodableList& list) {
  User decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]),
    std::get<std::string>(list[2]));
  auto& encodable_icon = list[3];
  if (!encodable_icon.IsNull()) {
    decoded.set_icon(std::get<std::string>(encodable_icon));
  }
  return decoded;
}

bool User::operator==(const User& other) const {
  return PigeonInternalDeepEquals(display_name_, other.display_name_) && PigeonInternalDeepEquals(name_, other.name_) && PigeonInternalDeepEquals(id_, other.id_) && PigeonInternalDeepEquals(icon_, other.icon_);
}

bool User::operator!=(const User& other) const {
  return !(*this == other);
}

size_t User::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(display_name_);
  result = result * 31 + PigeonInternalDeepHash(name_);
  result = result * 31 + PigeonInternalDeepHash(id_);
  result = result * 31 + PigeonInternalDeepHash(icon_);
  return result;
}

size_t PigeonInternalDeepHash(const User& v) {
  return v.Hash();
}

// AllowCredential

AllowCredential::AllowCredential(
  const std::string& type,
  const std::string& id,
  const EncodableList& transports)
 : type_(type),
    id_(id),
    transports_(transports) {}

const std::string& AllowCredential::type() const {
  return type_;
}

void AllowCredential::set_type(std::string_view value_arg) {
  type_ = value_arg;
}


const std::string& AllowCredential::id() const {
  return id_;
}

void AllowCredential::set_id(std::string_view value_arg) {
  id_ = value_arg;
}


const EncodableList& AllowCredential::transports() const {
  return transports_;
}

void AllowCredential::set_transports(const EncodableList& value_arg) {
  transports_ = value_arg;
}


EncodableList AllowCredential::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(EncodableValue(type_));
  list.push_back(EncodableValue(id_));
  list.push_back(EncodableValue(transports_));
  return list;
}

AllowCredential AllowCredential::FromEncodableList(const EncodableList& list) {
  AllowCredential decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]),
    std::get<EncodableList>(list[2]));
  return decoded;
}

bool AllowCredential::operator==(const AllowCredential& other) const {
  return PigeonInternalDeepEquals(type_, other.type_) && PigeonInternalDeepEquals(id_, other.id_) && PigeonInternalDeepEquals(transports_, other.transports_);
}

bool AllowCredential::operator!=(const AllowCredential& other) const {
  return !(*this == other);
}

size_t AllowCredential::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(type_);
  result = result * 31 + PigeonInternalDeepHash(id_);
  result = result * 31 + PigeonInternalDeepHash(transports_);
  return result;
}

size_t PigeonInternalDeepHash(const AllowCredential& v) {
  return v.Hash();
}

// ExcludeCredential

ExcludeCredential::ExcludeCredential(
  const std::string& type,
  const std::string& id)
 : type_(type),
    id_(id) {}

const std::string& ExcludeCredential::type() const {
  return type_;
}

void ExcludeCredential::set_type(std::string_view value_arg) {
  type_ = value_arg;
}


const std::string& ExcludeCredential::id() const {
  return id_;
}

void ExcludeCredential::set_id(std::string_view value_arg) {
  id_ = value_arg;
}


EncodableList ExcludeCredential::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(EncodableValue(type_));
  list.push_back(EncodableValue(id_));
  return list;
}

ExcludeCredential ExcludeCredential::FromEncodableList(const EncodableList& list) {
  ExcludeCredential decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]));
  return decoded;
}

bool ExcludeCredential::operator==(const ExcludeCredential& other) const {
  return PigeonInternalDeepEquals(type_, other.type_) && PigeonInternalDeepEquals(id_, other.id_);
}

bool ExcludeCredential::operator!=(const ExcludeCredential& other) const {
  return !(*this == other);
}

size_t ExcludeCredential::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(type_);
  result = result * 31 + PigeonInternalDeepHash(id_);
  return result;
}

size_t PigeonInternalDeepHash(const ExcludeCredential& v) {
  return v.Hash();
}

// AuthenticatorSelection

AuthenticatorSelection::AuthenticatorSelection(
  bool require_resident_key,
  const std::string& resident_key,
  const std::string& user_verification)
 : require_resident_key_(require_resident_key),
    resident_key_(resident_key),
    user_verification_(user_verification) {}

AuthenticatorSelection::AuthenticatorSelection(
  const std::string* authenticator_attachment,
  bool require_resident_key,
  const std::string& resident_key,
  const std::string& user_verification)
 : authenticator_attachment_(authenticator_attachment ? std::optional<std::string>(*authenticator_attachment) : std::nullopt),
    require_resident_key_(require_resident_key),
    resident_key_(resident_key),
    user_verification_(user_verification) {}

const std::string* AuthenticatorSelection::authenticator_attachment() const {
  return authenticator_attachment_ ? &(*authenticator_attachment_) : nullptr;
}

void AuthenticatorSelection::set_authenticator_attachment(const std::string_view* value_arg) {
  authenticator_attachment_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void AuthenticatorSelection::set_authenticator_attachment(std::string_view value_arg) {
  authenticator_attachment_ = value_arg;
}


bool AuthenticatorSelection::require_resident_key() const {
  return require_resident_key_;
}

void AuthenticatorSelection::set_require_resident_key(bool value_arg) {
  require_resident_key_ = value_arg;
}


const std::string& AuthenticatorSelection::resident_key() const {
  return resident_key_;
}

void AuthenticatorSelection::set_resident_key(std::string_view value_arg) {
  resident_key_ = value_arg;
}


const std::string& AuthenticatorSelection::user_verification() const {
  return user_verification_;
}

void AuthenticatorSelection::set_user_verification(std::string_view value_arg) {
  user_verification_ = value_arg;
}


EncodableList AuthenticatorSelection::ToEncodableList() const {
  EncodableList list;
  list.reserve(4);
  list.push_back(authenticator_attachment_ ? EncodableValue(*authenticator_attachment_) : EncodableValue());
  list.push_back(EncodableValue(require_resident_key_));
  list.push_back(EncodableValue(resident_key_));
  list.push_back(EncodableValue(user_verification_));
  return list;
}

AuthenticatorSelection AuthenticatorSelection::FromEncodableList(const EncodableList& list) {
  AuthenticatorSelection decoded(
    std::get<bool>(list[1]),
    std::get<std::string>(list[2]),
    std::get<std::string>(list[3]));
  auto& encodable_authenticator_attachment = list[0];
  if (!encodable_authenticator_attachment.IsNull()) {
    decoded.set_authenticator_attachment(std::get<std::string>(encodable_authenticator_attachment));
  }
  return decoded;
}

bool AuthenticatorSelection::operator==(const AuthenticatorSelection& other) const {
  return PigeonInternalDeepEquals(authenticator_attachment_, other.authenticator_attachment_) && PigeonInternalDeepEquals(require_resident_key_, other.require_resident_key_) && PigeonInternalDeepEquals(resident_key_, other.resident_key_) && PigeonInternalDeepEquals(user_verification_, other.user_verification_);
}

bool AuthenticatorSelection::operator!=(const AuthenticatorSelection& other) const {
  return !(*this == other);
}

size_t AuthenticatorSelection::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(authenticator_attachment_);
  result = result * 31 + PigeonInternalDeepHash(require_resident_key_);
  result = result * 31 + PigeonInternalDeepHash(resident_key_);
  result = result * 31 + PigeonInternalDeepHash(user_verification_);
  return result;
}

size_t PigeonInternalDeepHash(const AuthenticatorSelection& v) {
  return v.Hash();
}

// RegisterResponse

RegisterResponse::RegisterResponse(
  const std::string& id,
  const std::string& raw_id,
  const std::string& client_data_j_s_o_n,
  const std::string& attestation_object,
  const EncodableList& transports)
 : id_(id),
    raw_id_(raw_id),
    client_data_j_s_o_n_(client_data_j_s_o_n),
    attestation_object_(attestation_object),
    transports_(transports) {}

RegisterResponse::RegisterResponse(
  const std::string& id,
  const std::string& raw_id,
  const std::string& client_data_j_s_o_n,
  const std::string& attestation_object,
  const EncodableList& transports,
  const bool* prf_enabled)
 : id_(id),
    raw_id_(raw_id),
    client_data_j_s_o_n_(client_data_j_s_o_n),
    attestation_object_(attestation_object),
    transports_(transports),
    prf_enabled_(prf_enabled ? std::optional<bool>(*prf_enabled) : std::nullopt) {}

const std::string& RegisterResponse::id() const {
  return id_;
}

void RegisterResponse::set_id(std::string_view value_arg) {
  id_ = value_arg;
}


const std::string& RegisterResponse::raw_id() const {
  return raw_id_;
}

void RegisterResponse::set_raw_id(std::string_view value_arg) {
  raw_id_ = value_arg;
}


const std::string& RegisterResponse::client_data_j_s_o_n() const {
  return client_data_j_s_o_n_;
}

void RegisterResponse::set_client_data_j_s_o_n(std::string_view value_arg) {
  client_data_j_s_o_n_ = value_arg;
}


const std::string& RegisterResponse::attestation_object() const {
  return attestation_object_;
}

void RegisterResponse::set_attestation_object(std::string_view value_arg) {
  attestation_object_ = value_arg;
}


const EncodableList& RegisterResponse::transports() const {
  return transports_;
}

void RegisterResponse::set_transports(const EncodableList& value_arg) {
  transports_ = value_arg;
}


const bool* RegisterResponse::prf_enabled() const {
  return prf_enabled_ ? &(*prf_enabled_) : nullptr;
}

void RegisterResponse::set_prf_enabled(const bool* value_arg) {
  prf_enabled_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void RegisterResponse::set_prf_enabled(bool value_arg) {
  prf_enabled_ = value_arg;
}


EncodableList RegisterResponse::ToEncodableList() const {
  EncodableList list;
  list.reserve(6);
  list.push_back(EncodableValue(id_));
  list.push_back(EncodableValue(raw_id_));
  list.push_back(EncodableValue(client_data_j_s_o_n_));
  list.push_back(EncodableValue(attestation_object_));
  list.push_back(EncodableValue(transports_));
  list.push_back(prf_enabled_ ? EncodableValue(*prf_enabled_) : EncodableValue());
  return list;
}

RegisterResponse RegisterResponse::FromEncodableList(const EncodableList& list) {
  RegisterResponse decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]),
    std::get<std::string>(list[2]),
    std::get<std::string>(list[3]),
    std::get<EncodableList>(list[4]));
  auto& encodable_prf_enabled = list[5];
  if (!encodable_prf_enabled.IsNull()) {
    decoded.set_prf_enabled(std::get<bool>(encodable_prf_enabled));
  }
  return decoded;
}

bool RegisterResponse::operator==(const RegisterResponse& other) const {
  return PigeonInternalDeepEquals(id_, other.id_) && PigeonInternalDeepEquals(raw_id_, other.raw_id_) && PigeonInternalDeepEquals(client_data_j_s_o_n_, other.client_data_j_s_o_n_) && PigeonInternalDeepEquals(attestation_object_, other.attestation_object_) && PigeonInternalDeepEquals(transports_, other.transports_) && PigeonInternalDeepEquals(prf_enabled_, other.prf_enabled_);
}

bool RegisterResponse::operator!=(const RegisterResponse& other) const {
  return !(*this == other);
}

size_t RegisterResponse::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(id_);
  result = result * 31 + PigeonInternalDeepHash(raw_id_);
  result = result * 31 + PigeonInternalDeepHash(client_data_j_s_o_n_);
  result = result * 31 + PigeonInternalDeepHash(attestation_object_);
  result = result * 31 + PigeonInternalDeepHash(transports_);
  result = result * 31 + PigeonInternalDeepHash(prf_enabled_);
  return result;
}

size_t PigeonInternalDeepHash(const RegisterResponse& v) {
  return v.Hash();
}

// AuthenticateResponse

AuthenticateResponse::AuthenticateResponse(
  const std::string& id,
  const std::string& raw_id,
  const std::string& client_data_j_s_o_n,
  const std::string& authenticator_data,
  const std::string& signature,
  const std::string& user_handle)
 : id_(id),
    raw_id_(raw_id),
    client_data_j_s_o_n_(client_data_j_s_o_n),
    authenticator_data_(authenticator_data),
    signature_(signature),
    user_handle_(user_handle) {}

AuthenticateResponse::AuthenticateResponse(
  const std::string& id,
  const std::string& raw_id,
  const std::string& client_data_j_s_o_n,
  const std::string& authenticator_data,
  const std::string& signature,
  const std::string& user_handle,
  const std::string* prf_result_first)
 : id_(id),
    raw_id_(raw_id),
    client_data_j_s_o_n_(client_data_j_s_o_n),
    authenticator_data_(authenticator_data),
    signature_(signature),
    user_handle_(user_handle),
    prf_result_first_(prf_result_first ? std::optional<std::string>(*prf_result_first) : std::nullopt) {}

const std::string& AuthenticateResponse::id() const {
  return id_;
}

void AuthenticateResponse::set_id(std::string_view value_arg) {
  id_ = value_arg;
}


const std::string& AuthenticateResponse::raw_id() const {
  return raw_id_;
}

void AuthenticateResponse::set_raw_id(std::string_view value_arg) {
  raw_id_ = value_arg;
}


const std::string& AuthenticateResponse::client_data_j_s_o_n() const {
  return client_data_j_s_o_n_;
}

void AuthenticateResponse::set_client_data_j_s_o_n(std::string_view value_arg) {
  client_data_j_s_o_n_ = value_arg;
}


const std::string& AuthenticateResponse::authenticator_data() const {
  return authenticator_data_;
}

void AuthenticateResponse::set_authenticator_data(std::string_view value_arg) {
  authenticator_data_ = value_arg;
}


const std::string& AuthenticateResponse::signature() const {
  return signature_;
}

void AuthenticateResponse::set_signature(std::string_view value_arg) {
  signature_ = value_arg;
}


const std::string& AuthenticateResponse::user_handle() const {
  return user_handle_;
}

void AuthenticateResponse::set_user_handle(std::string_view value_arg) {
  user_handle_ = value_arg;
}


const std::string* AuthenticateResponse::prf_result_first() const {
  return prf_result_first_ ? &(*prf_result_first_) : nullptr;
}

void AuthenticateResponse::set_prf_result_first(const std::string_view* value_arg) {
  prf_result_first_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void AuthenticateResponse::set_prf_result_first(std::string_view value_arg) {
  prf_result_first_ = value_arg;
}


EncodableList AuthenticateResponse::ToEncodableList() const {
  EncodableList list;
  list.reserve(7);
  list.push_back(EncodableValue(id_));
  list.push_back(EncodableValue(raw_id_));
  list.push_back(EncodableValue(client_data_j_s_o_n_));
  list.push_back(EncodableValue(authenticator_data_));
  list.push_back(EncodableValue(signature_));
  list.push_back(EncodableValue(user_handle_));
  list.push_back(prf_result_first_ ? EncodableValue(*prf_result_first_) : EncodableValue());
  return list;
}

AuthenticateResponse AuthenticateResponse::FromEncodableList(const EncodableList& list) {
  AuthenticateResponse decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]),
    std::get<std::string>(list[2]),
    std::get<std::string>(list[3]),
    std::get<std::string>(list[4]),
    std::get<std::string>(list[5]));
  auto& encodable_prf_result_first = list[6];
  if (!encodable_prf_result_first.IsNull()) {
    decoded.set_prf_result_first(std::get<std::string>(encodable_prf_result_first));
  }
  return decoded;
}

bool AuthenticateResponse::operator==(const AuthenticateResponse& other) const {
  return PigeonInternalDeepEquals(id_, other.id_) && PigeonInternalDeepEquals(raw_id_, other.raw_id_) && PigeonInternalDeepEquals(client_data_j_s_o_n_, other.client_data_j_s_o_n_) && PigeonInternalDeepEquals(authenticator_data_, other.authenticator_data_) && PigeonInternalDeepEquals(signature_, other.signature_) && PigeonInternalDeepEquals(user_handle_, other.user_handle_) && PigeonInternalDeepEquals(prf_result_first_, other.prf_result_first_);
}

bool AuthenticateResponse::operator!=(const AuthenticateResponse& other) const {
  return !(*this == other);
}

size_t AuthenticateResponse::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(id_);
  result = result * 31 + PigeonInternalDeepHash(raw_id_);
  result = result * 31 + PigeonInternalDeepHash(client_data_j_s_o_n_);
  result = result * 31 + PigeonInternalDeepHash(authenticator_data_);
  result = result * 31 + PigeonInternalDeepHash(signature_);
  result = result * 31 + PigeonInternalDeepHash(user_handle_);
  result = result * 31 + PigeonInternalDeepHash(prf_result_first_);
  return result;
}

size_t PigeonInternalDeepHash(const AuthenticateResponse& v) {
  return v.Hash();
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  ::flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        return CustomEncodableValue(RelyingParty::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 130: {
        return CustomEncodableValue(PubKeyCredParam::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 131: {
        return CustomEncodableValue(User::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 132: {
        return CustomEncodableValue(AllowCredential::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 133: {
        return CustomEncodableValue(ExcludeCredential::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 134: {
        return CustomEncodableValue(AuthenticatorSelection::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 135: {
        return CustomEncodableValue(RegisterResponse::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 136: {
        return CustomEncodableValue(AuthenticateResponse::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return ::flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  ::flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(RelyingParty)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(std::any_cast<RelyingParty>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PubKeyCredParam)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(std::any_cast<PubKeyCredParam>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(User)) {
      stream->WriteByte(131);
      WriteValue(EncodableValue(std::any_cast<User>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(AllowCredential)) {
      stream->WriteByte(132);
      WriteValue(EncodableValue(std::any_cast<AllowCredential>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(ExcludeCredential)) {
      stream->WriteByte(133);
      WriteValue(EncodableValue(std::any_cast<ExcludeCredential>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(AuthenticatorSelection)) {
      stream->WriteByte(134);
      WriteValue(EncodableValue(std::any_cast<AuthenticatorSelection>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(RegisterResponse)) {
      stream->WriteByte(135);
      WriteValue(EncodableValue(std::any_cast<RegisterResponse>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(AuthenticateResponse)) {
      stream->WriteByte(136);
      WriteValue(EncodableValue(std::any_cast<AuthenticateResponse>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  ::flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by PasskeysApi.
const ::flutter::StandardMessageCodec& PasskeysApi::GetCodec() {
  return ::flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `PasskeysApi` to handle messages through the `binary_messenger`.
void PasskeysApi::SetUp(
  ::flutter::BinaryMessenger* binary_messenger,
  PasskeysApi* api) {
  PasskeysApi::SetUp(binary_messenger, api, "");
}

void PasskeysApi::SetUp(
  ::flutter::BinaryMessenger* binary_messenger,
  PasskeysApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.passkeys_windows.PasskeysApi.canAuthenticate" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->CanAuthenticate([reply](ErrorOr<bool>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.passkeys_windows.PasskeysApi.hasPasskeySupport" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->HasPasskeySupport([reply](ErrorOr<bool>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.passkeys_windows.PasskeysApi.register" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_challenge_arg = args.at(0);
          if (encodable_challenge_arg.IsNull()) {
            reply(WrapError("challenge_arg unexpectedly null."));
            return;
          }
          const auto& challenge_arg = std::get<std::string>(encodable_challenge_arg);
          const auto& encodable_relying_party_arg = args.at(1);
          if (encodable_relying_party_arg.IsNull()) {
            reply(WrapError("relying_party_arg unexpectedly null."));
            return;
          }
          const auto& relying_party_arg = std::any_cast<const RelyingParty&>(std::get<CustomEncodableValue>(encodable_relying_party_arg));
          const auto& encodable_user_arg = args.at(2);
          if (encodable_user_arg.IsNull()) {
            reply(WrapError("user_arg unexpectedly null."));
            return;
          }
          const auto& user_arg = std::any_cast<const User&>(std::get<CustomEncodableValue>(encodable_user_arg));
          const auto& encodable_authenticator_selection_arg = args.at(3);
          const auto* authenticator_selection_arg = encodable_authenticator_selection_arg.IsNull() ? nullptr : &(std::any_cast<const AuthenticatorSelection&>(std::get<CustomEncodableValue>(encodable_authenticator_selection_arg)));
          const auto& encodable_pub_key_cred_params_arg = args.at(4);
          const auto* pub_key_cred_params_arg = std::get_if<EncodableList>(&encodable_pub_key_cred_params_arg);
          const auto& encodable_timeout_arg = args.at(5);
          const auto* timeout_arg = std::get_if<int64_t>(&encodable_timeout_arg);
          const auto& encodable_attestation_arg = args.at(6);
          const auto* attestation_arg = std::get_if<std::string>(&encodable_attestation_arg);
          const auto& encodable_exclude_credentials_arg = args.at(7);
          if (encodable_exclude_credentials_arg.IsNull()) {
            reply(WrapError("exclude_credentials_arg unexpectedly null."));
            return;
          }
          const auto& exclude_credentials_arg = std::get<EncodableList>(encodable_exclude_credentials_arg);
          const auto& encodable_prf_arg = args.at(8);
          const auto* prf_arg = std::get_if<std::string>(&encodable_prf_arg);
          api->Register(challenge_arg, relying_party_arg, user_arg, authenticator_selection_arg, pub_key_cred_params_arg, timeout_arg, attestation_arg, exclude_credentials_arg, prf_arg, [reply](ErrorOr<RegisterResponse>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.passkeys_windows.PasskeysApi.authenticate" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_relying_party_id_arg = args.at(0);
          if (encodable_relying_party_id_arg.IsNull()) {
            reply(WrapError("relying_party_id_arg unexpectedly null."));
            return;
          }
          const auto& relying_party_id_arg = std::get<std::string>(encodable_relying_party_id_arg);
          const auto& encodable_challenge_arg = args.at(1);
          if (encodable_challenge_arg.IsNull()) {
            reply(WrapError("challenge_arg unexpectedly null."));
            return;
          }
          const auto& challenge_arg = std::get<std::string>(encodable_challenge_arg);
          const auto& encodable_timeout_arg = args.at(2);
          const auto* timeout_arg = std::get_if<int64_t>(&encodable_timeout_arg);
          const auto& encodable_user_verification_arg = args.at(3);
          const auto* user_verification_arg = std::get_if<std::string>(&encodable_user_verification_arg);
          const auto& encodable_allow_credentials_arg = args.at(4);
          const auto* allow_credentials_arg = std::get_if<EncodableList>(&encodable_allow_credentials_arg);
          const auto& encodable_prefer_immediately_available_credentials_arg = args.at(5);
          const auto* prefer_immediately_available_credentials_arg = std::get_if<bool>(&encodable_prefer_immediately_available_credentials_arg);
          const auto& encodable_prf_arg = args.at(6);
          const auto* prf_arg = std::get_if<std::string>(&encodable_prf_arg);
          api->Authenticate(relying_party_id_arg, challenge_arg, timeout_arg, user_verification_arg, allow_credentials_arg, prefer_immediately_available_credentials_arg, prf_arg, [reply](ErrorOr<AuthenticateResponse>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.passkeys_windows.PasskeysApi.cancelCurrentAuthenticatorOperation" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->CancelCurrentAuthenticatorOperation([reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue PasskeysApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue PasskeysApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

}  // namespace passkeys_windows
