// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace passkeys_windows {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class PasskeysApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


// Represents a relying party
//
// Generated class from Pigeon that represents data sent in messages.
class RelyingParty {
 public:
  // Constructs an object setting all fields.
  explicit RelyingParty(
    const std::string& name,
    const std::string& id);

  // Name of the relying party
  const std::string& name() const;
  void set_name(std::string_view value_arg);

  // ID of the relying party
  const std::string& id() const;
  void set_id(std::string_view value_arg);


 private:
  static RelyingParty FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class PasskeysApi;
  friend class PasskeysApiCodecSerializer;
  std::string name_;
  std::string id_;

};


// Represents a public key credential parameter
//
// Generated class from Pigeon that represents data sent in messages.
class PubKeyCredParam {
 public:
  // Constructs an object setting all fields.
  explicit PubKeyCredParam(
    const std::string& type,
    int64_t alg);

  // The type
  const std::string& type() const;
  void set_type(std::string_view value_arg);

  // The algorithm
  int64_t alg() const;
  void set_alg(int64_t value_arg);


 private:
  static PubKeyCredParam FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class PasskeysApi;
  friend class PasskeysApiCodecSerializer;
  std::string type_;
  int64_t alg_;

};


// Represents a user
//
// Generated class from Pigeon that represents data sent in messages.
class User {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit User(
    const std::string& display_name,
    const std::string& name,
    const std::string& id);

  // Constructs an object setting all fields.
  explicit User(
    const std::string& display_name,
    const std::string& name,
    const std::string& id,
    const std::string* icon);

  // The display name
  const std::string& display_name() const;
  void set_display_name(std::string_view value_arg);

  // The name
  const std::string& name() const;
  void set_name(std::string_view value_arg);

  // The ID
  const std::string& id() const;
  void set_id(std::string_view value_arg);

  // The icon
  const std::string* icon() const;
  void set_icon(const std::string_view* value_arg);
  void set_icon(std::string_view value_arg);


 private:
  static User FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class PasskeysApi;
  friend class PasskeysApiCodecSerializer;
  std::string display_name_;
  std::string name_;
  std::string id_;
  std::optional<std::string> icon_;

};


// Represents an allowed credential
//
// Generated class from Pigeon that represents data sent in messages.
class AllowCredential {
 public:
  // Constructs an object setting all fields.
  explicit AllowCredential(
    const std::string& type,
    const std::string& id,
    const flutter::EncodableList& transports);

  // The type
  const std::string& type() const;
  void set_type(std::string_view value_arg);

  // The ID
  const std::string& id() const;
  void set_id(std::string_view value_arg);

  // The transports
  const flutter::EncodableList& transports() const;
  void set_transports(const flutter::EncodableList& value_arg);


 private:
  static AllowCredential FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class PasskeysApi;
  friend class PasskeysApiCodecSerializer;
  std::string type_;
  std::string id_;
  flutter::EncodableList transports_;

};


// Represents an exclude credential
//
// Generated class from Pigeon that represents data sent in messages.
class ExcludeCredential {
 public:
  // Constructs an object setting all fields.
  explicit ExcludeCredential(
    const std::string& type,
    const std::string& id);

  // The type
  const std::string& type() const;
  void set_type(std::string_view value_arg);

  // The ID
  const std::string& id() const;
  void set_id(std::string_view value_arg);


 private:
  static ExcludeCredential FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class PasskeysApi;
  friend class PasskeysApiCodecSerializer;
  std::string type_;
  std::string id_;

};


// Represents an authenticator selection
//
// Generated class from Pigeon that represents data sent in messages.
class AuthenticatorSelection {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit AuthenticatorSelection(
    bool require_resident_key,
    const std::string& resident_key,
    const std::string& user_verification);

  // Constructs an object setting all fields.
  explicit AuthenticatorSelection(
    const std::string* authenticator_attachment,
    bool require_resident_key,
    const std::string& resident_key,
    const std::string& user_verification);

  // The authenticator attachment
  const std::string* authenticator_attachment() const;
  void set_authenticator_attachment(const std::string_view* value_arg);
  void set_authenticator_attachment(std::string_view value_arg);

  // Whether a resident key is required
  bool require_resident_key() const;
  void set_require_resident_key(bool value_arg);

  // The resident key
  const std::string& resident_key() const;
  void set_resident_key(std::string_view value_arg);

  // The user verification
  const std::string& user_verification() const;
  void set_user_verification(std::string_view value_arg);


 private:
  static AuthenticatorSelection FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class PasskeysApi;
  friend class PasskeysApiCodecSerializer;
  std::optional<std::string> authenticator_attachment_;
  bool require_resident_key_;
  std::string resident_key_;
  std::string user_verification_;

};


// Represents a register response
//
// Generated class from Pigeon that represents data sent in messages.
class RegisterResponse {
 public:
  // Constructs an object setting all fields.
  explicit RegisterResponse(
    const std::string& id,
    const std::string& raw_id,
    const std::string& client_data_j_s_o_n,
    const std::string& attestation_object,
    const flutter::EncodableList& transports);

  // The ID
  const std::string& id() const;
  void set_id(std::string_view value_arg);

  // The raw ID
  const std::string& raw_id() const;
  void set_raw_id(std::string_view value_arg);

  // The client data JSON
  const std::string& client_data_j_s_o_n() const;
  void set_client_data_j_s_o_n(std::string_view value_arg);

  // The attestation object
  const std::string& attestation_object() const;
  void set_attestation_object(std::string_view value_arg);

  // The supported transports for the authenticator
  const flutter::EncodableList& transports() const;
  void set_transports(const flutter::EncodableList& value_arg);


 private:
  static RegisterResponse FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class PasskeysApi;
  friend class PasskeysApiCodecSerializer;
  std::string id_;
  std::string raw_id_;
  std::string client_data_j_s_o_n_;
  std::string attestation_object_;
  flutter::EncodableList transports_;

};


// Represents an authenticate response
//
// Generated class from Pigeon that represents data sent in messages.
class AuthenticateResponse {
 public:
  // Constructs an object setting all fields.
  explicit AuthenticateResponse(
    const std::string& id,
    const std::string& raw_id,
    const std::string& client_data_j_s_o_n,
    const std::string& authenticator_data,
    const std::string& signature,
    const std::string& user_handle);

  // The ID
  const std::string& id() const;
  void set_id(std::string_view value_arg);

  // The raw ID
  const std::string& raw_id() const;
  void set_raw_id(std::string_view value_arg);

  // The client data JSON
  const std::string& client_data_j_s_o_n() const;
  void set_client_data_j_s_o_n(std::string_view value_arg);

  // The authenticator data
  const std::string& authenticator_data() const;
  void set_authenticator_data(std::string_view value_arg);

  // The signature
  const std::string& signature() const;
  void set_signature(std::string_view value_arg);

  // The user handle
  const std::string& user_handle() const;
  void set_user_handle(std::string_view value_arg);


 private:
  static AuthenticateResponse FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class PasskeysApi;
  friend class PasskeysApiCodecSerializer;
  std::string id_;
  std::string raw_id_;
  std::string client_data_j_s_o_n_;
  std::string authenticator_data_;
  std::string signature_;
  std::string user_handle_;

};

class PasskeysApiCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PasskeysApiCodecSerializer();
  inline static PasskeysApiCodecSerializer& GetInstance() {
    static PasskeysApiCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class PasskeysApi {
 public:
  PasskeysApi(const PasskeysApi&) = delete;
  PasskeysApi& operator=(const PasskeysApi&) = delete;
  virtual ~PasskeysApi() {}
  virtual void CanAuthenticate(std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void HasPasskeySupport(std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void Register(
    const std::string& challenge,
    const RelyingParty& relying_party,
    const User& user,
    const AuthenticatorSelection* authenticator_selection,
    const flutter::EncodableList* pub_key_cred_params,
    const int64_t* timeout,
    const std::string* attestation,
    const flutter::EncodableList& exclude_credentials,
    std::function<void(ErrorOr<RegisterResponse> reply)> result) = 0;
  virtual void Authenticate(
    const std::string& relying_party_id,
    const std::string& challenge,
    const int64_t* timeout,
    const std::string* user_verification,
    const flutter::EncodableList* allow_credentials,
    const bool* prefer_immediately_available_credentials,
    std::function<void(ErrorOr<AuthenticateResponse> reply)> result) = 0;
  virtual void CancelCurrentAuthenticatorOperation(std::function<void(std::optional<FlutterError> reply)> result) = 0;

  // The codec used by PasskeysApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `PasskeysApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    PasskeysApi* api);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  PasskeysApi() = default;

};
}  // namespace passkeys_windows
#endif  // PIGEON_MESSAGES_G_H_
