// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Represents a relying party
class RelyingParty {
  RelyingParty({
    required this.name,
    required this.id,
  });

  /// Name of the relying party
  String name;

  /// ID of the relying party
  String id;

  List<Object?> _toList() {
    return <Object?>[
      name,
      id,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RelyingParty decode(Object result) {
    result as List<Object?>;
    return RelyingParty(
      name: result[0]! as String,
      id: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RelyingParty || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) && _deepEquals(id, other.id);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Represents a credential
class CredentialType {
  CredentialType({
    required this.type,
    required this.id,
    required this.transports,
  });

  /// The type of the credential.
  String type;

  /// The ID of the credential.
  String id;

  /// The transports of the credential.
  List<String?> transports;

  List<Object?> _toList() {
    return <Object?>[
      type,
      id,
      transports,
    ];
  }

  Object encode() {
    return _toList();
  }

  static CredentialType decode(Object result) {
    result as List<Object?>;
    return CredentialType(
      type: result[0]! as String,
      id: result[1]! as String,
      transports: (result[2]! as List<Object?>).cast<String?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CredentialType || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type) &&
        _deepEquals(id, other.id) &&
        _deepEquals(transports, other.transports);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Represents a user
class User {
  User({
    required this.name,
    required this.id,
  });

  /// The name
  String name;

  /// The ID
  String id;

  List<Object?> _toList() {
    return <Object?>[
      name,
      id,
    ];
  }

  Object encode() {
    return _toList();
  }

  static User decode(Object result) {
    result as List<Object?>;
    return User(
      name: result[0]! as String,
      id: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! User || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) && _deepEquals(id, other.id);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Represents a register response
class RegisterResponse {
  RegisterResponse({
    required this.id,
    required this.rawId,
    required this.clientDataJSON,
    required this.attestationObject,
    required this.transports,
    this.clientExtensionResults = const {},
  });

  /// The ID
  String id;

  /// The raw ID
  String rawId;

  /// The client data JSON
  String clientDataJSON;

  /// The attestation object
  String attestationObject;

  /// The supported transports for the authenticator
  List<String?> transports;

  /// The clientExtensionResults - PRF results
  Map<String?, Object?>? clientExtensionResults;

  List<Object?> _toList() {
    return <Object?>[
      id,
      rawId,
      clientDataJSON,
      attestationObject,
      transports,
      clientExtensionResults,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RegisterResponse decode(Object result) {
    result as List<Object?>;
    return RegisterResponse(
      id: result[0]! as String,
      rawId: result[1]! as String,
      clientDataJSON: result[2]! as String,
      attestationObject: result[3]! as String,
      transports: (result[4]! as List<Object?>).cast<String?>(),
      clientExtensionResults: (result[5] as Map<Object?, Object?>?)
          ?.cast<String?, Object?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RegisterResponse || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(rawId, other.rawId) &&
        _deepEquals(clientDataJSON, other.clientDataJSON) &&
        _deepEquals(attestationObject, other.attestationObject) &&
        _deepEquals(transports, other.transports) &&
        _deepEquals(clientExtensionResults, other.clientExtensionResults);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Represents an authenticate response
class AuthenticateResponse {
  AuthenticateResponse({
    required this.id,
    required this.rawId,
    required this.clientDataJSON,
    required this.authenticatorData,
    required this.signature,
    this.userHandle,
    this.clientExtensionResults = const {},
  });

  /// The ID
  String id;

  /// The raw ID
  String rawId;

  /// The client data JSON
  String clientDataJSON;

  /// The authenticator data
  String authenticatorData;

  /// Signed challenge
  String signature;

  String? userHandle;

  /// The clientExtensionResults - PRF results
  Map<String?, Object?>? clientExtensionResults;

  List<Object?> _toList() {
    return <Object?>[
      id,
      rawId,
      clientDataJSON,
      authenticatorData,
      signature,
      userHandle,
      clientExtensionResults,
    ];
  }

  Object encode() {
    return _toList();
  }

  static AuthenticateResponse decode(Object result) {
    result as List<Object?>;
    return AuthenticateResponse(
      id: result[0]! as String,
      rawId: result[1]! as String,
      clientDataJSON: result[2]! as String,
      authenticatorData: result[3]! as String,
      signature: result[4]! as String,
      userHandle: result[5] as String?,
      clientExtensionResults: (result[6] as Map<Object?, Object?>?)
          ?.cast<String?, Object?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AuthenticateResponse || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(rawId, other.rawId) &&
        _deepEquals(clientDataJSON, other.clientDataJSON) &&
        _deepEquals(authenticatorData, other.authenticatorData) &&
        _deepEquals(signature, other.signature) &&
        _deepEquals(userHandle, other.userHandle) &&
        _deepEquals(clientExtensionResults, other.clientExtensionResults);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is RelyingParty) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is CredentialType) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is User) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is RegisterResponse) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is AuthenticateResponse) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return RelyingParty.decode(readValue(buffer)!);
      case 130:
        return CredentialType.decode(readValue(buffer)!);
      case 131:
        return User.decode(readValue(buffer)!);
      case 132:
        return RegisterResponse.decode(readValue(buffer)!);
      case 133:
        return AuthenticateResponse.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class PasskeysApi {
  /// Constructor for [PasskeysApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PasskeysApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<bool> canAuthenticate() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.passkeys_darwin.PasskeysApi.canAuthenticate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> hasBiometrics() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.passkeys_darwin.PasskeysApi.hasBiometrics$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<RegisterResponse> register(
    String challenge,
    RelyingParty relyingParty,
    User user,
    List<CredentialType> excludeCredentials,
    List<int> pubKeyCredValues,
    bool canBePlatformAuthenticator,
    bool canBeSecurityKey,
    String? residentKeyPreference,
    String? attestationPreference,
    String? salt,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.passkeys_darwin.PasskeysApi.register$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[
        challenge,
        relyingParty,
        user,
        excludeCredentials,
        pubKeyCredValues,
        canBePlatformAuthenticator,
        canBeSecurityKey,
        residentKeyPreference,
        attestationPreference,
        salt,
      ],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as RegisterResponse;
  }

  Future<AuthenticateResponse> authenticate(
    String relyingPartyId,
    String challenge,
    bool conditionalUI,
    List<CredentialType> allowedCredentials,
    bool preferImmediatelyAvailableCredentials,
    String? salt,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.passkeys_darwin.PasskeysApi.authenticate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[
        relyingPartyId,
        challenge,
        conditionalUI,
        allowedCredentials,
        preferImmediatelyAvailableCredentials,
        salt,
      ],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as AuthenticateResponse;
  }

  Future<void> cancelCurrentAuthenticatorOperation() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.passkeys_darwin.PasskeysApi.cancelCurrentAuthenticatorOperation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> signalUnknownCredential(
    String relyingPartyId,
    String credentialId,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.passkeys_darwin.PasskeysApi.signalUnknownCredential$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[relyingPartyId, credentialId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> signalAllAcceptedCredentials(
    String relyingPartyId,
    String userId,
    List<String> allAcceptedCredentialIds,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.passkeys_darwin.PasskeysApi.signalAllAcceptedCredentials$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[relyingPartyId, userId, allAcceptedCredentialIds],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}
