name: flutter-passkeys
repository: https://github.com/corbado/flutter-passkeys
packages:
  - packages/**

scripts:
  format:
    description: Format Dart code.
    run: dart format .

  format:check:
    description: Check formatting of Dart code.
    run: dart format --output none --set-exit-if-changed .

  analyze:
    description: Analyze Dart code.
    run: dart analyze . --fatal-infos

  test:
    description: Run tests in a specific package.
    run: dart test
    exec:
      concurrency: 1
    packageFilters:
      dirExists:
        - test