// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW5L6chVyqM8SMgBpjgio2MhvIsKV8OJU',
    appId: '1:734610402726:web:31c45d25a0713c82427367',
    messagingSenderId: '734610402726',
    projectId: 'example-corbado-auth',
    authDomain: 'example-corbado-auth.firebaseapp.com',
    storageBucket: 'example-corbado-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-R8uiOLF-4qdEWw7nRc3LqLpsPYgi0sU',
    appId: '1:734610402726:android:9e82ce9c8f6a013d427367',
    messagingSenderId: '734610402726',
    projectId: 'example-corbado-auth',
    storageBucket: 'example-corbado-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd4xUQkD3QnIy3txwIDUC__yVFoQfZzW4',
    appId: '1:734610402726:ios:3883450c3d23dac3427367',
    messagingSenderId: '734610402726',
    projectId: 'example-corbado-auth',
    storageBucket: 'example-corbado-auth.appspot.com',
    iosBundleId: 'com.corbado.corbadoauthfirebase.example',
  );
}
