// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUXToLab53kDIQHMQYK40I-X_i1PntDtI',
    appId: '1:696582919492:web:b9707a7c73875c9f4a3311',
    messagingSenderId: '696582919492',
    projectId: 'corbado',
    authDomain: 'corbado.firebaseapp.com',
    storageBucket: 'corbado.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbs96K5pV6oIFan-osmo576eC8Jq5HJKE',
    appId: '1:696582919492:android:c64c8ab920ddb3ee4a3311',
    messagingSenderId: '696582919492',
    projectId: 'corbado',
    storageBucket: 'corbado.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAOsjrXDUETBKxpA9VhEdThQqwAFD9lfo',
    appId: '1:696582919492:ios:84e8224959db48944a3311',
    messagingSenderId: '696582919492',
    projectId: 'corbado',
    storageBucket: 'corbado.appspot.com',
    iosBundleId: 'com.corbado.corbadoauthfirebase.example',
  );
}
