// Autogenerated from Pigeon (v10.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct RelyingParty {
  var name: String
  var id: String

  static func fromList(_ list: [Any?]) -> RelyingParty? {
    let name = list[0] as! String
    let id = list[1] as! String

    return RelyingParty(
      name: name,
      id: id
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      id,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct User {
  var name: String
  var id: String

  static func fromList(_ list: [Any?]) -> User? {
    let name = list[0] as! String
    let id = list[1] as! String

    return User(
      name: name,
      id: id
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      id,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RegisterResponse {
  var id: String
  var rawId: String
  var clientDataJSON: String
  var attestationObject: String

  static func fromList(_ list: [Any?]) -> RegisterResponse? {
    let id = list[0] as! String
    let rawId = list[1] as! String
    let clientDataJSON = list[2] as! String
    let attestationObject = list[3] as! String

    return RegisterResponse(
      id: id,
      rawId: rawId,
      clientDataJSON: clientDataJSON,
      attestationObject: attestationObject
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      rawId,
      clientDataJSON,
      attestationObject,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AuthenticateResponse {
  var id: String
  var rawId: String
  var clientDataJSON: String
  var authenticatorData: String
  var signature: String

  static func fromList(_ list: [Any?]) -> AuthenticateResponse? {
    let id = list[0] as! String
    let rawId = list[1] as! String
    let clientDataJSON = list[2] as! String
    let authenticatorData = list[3] as! String
    let signature = list[4] as! String

    return AuthenticateResponse(
      id: id,
      rawId: rawId,
      clientDataJSON: clientDataJSON,
      authenticatorData: authenticatorData,
      signature: signature
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      rawId,
      clientDataJSON,
      authenticatorData,
      signature,
    ]
  }
}

private class PasskeysApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return AuthenticateResponse.fromList(self.readValue() as! [Any?])
      case 129:
        return RegisterResponse.fromList(self.readValue() as! [Any?])
      case 130:
        return RelyingParty.fromList(self.readValue() as! [Any?])
      case 131:
        return User.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class PasskeysApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AuthenticateResponse {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? RegisterResponse {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? RelyingParty {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? User {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PasskeysApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PasskeysApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PasskeysApiCodecWriter(data: data)
  }
}

class PasskeysApiCodec: FlutterStandardMessageCodec {
  static let shared = PasskeysApiCodec(readerWriter: PasskeysApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PasskeysApi {
  func canAuthenticate() throws -> Bool
  func register(challenge: String, relyingParty: RelyingParty, user: User, completion: @escaping (Result<RegisterResponse, Error>) -> Void)
  func authenticate(relyingPartyId: String, challenge: String, completion: @escaping (Result<AuthenticateResponse, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PasskeysApiSetup {
  /// The codec used by PasskeysApi.
  static var codec: FlutterStandardMessageCodec { PasskeysApiCodec.shared }
  /// Sets up an instance of `PasskeysApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PasskeysApi?) {
    let canAuthenticateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.PasskeysApi.canAuthenticate", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      canAuthenticateChannel.setMessageHandler { _, reply in
        do {
          let result = try api.canAuthenticate()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      canAuthenticateChannel.setMessageHandler(nil)
    }
    let registerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.PasskeysApi.register", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      registerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let challengeArg = args[0] as! String
        let relyingPartyArg = args[1] as! RelyingParty
        let userArg = args[2] as! User
        api.register(challenge: challengeArg, relyingParty: relyingPartyArg, user: userArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      registerChannel.setMessageHandler(nil)
    }
    let authenticateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.PasskeysApi.authenticate", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      authenticateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let relyingPartyIdArg = args[0] as! String
        let challengeArg = args[1] as! String
        api.authenticate(relyingPartyId: relyingPartyIdArg, challenge: challengeArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      authenticateChannel.setMessageHandler(nil)
    }
  }
}
