name: passkeys_doctor
description: "Internal debugging tools used to help with passkeys package."
homepage: https://docs.corbado.com/overview/welcome
repository: https://github.com/corbado/flutter-passkeys/tree/main/packages/passkeys/passkeys_doctor
version: 1.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  device_info_plus: ^11.2.0
  package_info_plus: ^8.3.0
  passkeys_platform_interface: ^2.3.1
  passkeys_ios: ^2.6.1

dev_dependencies:
  pigeon: ^25.3.1

flutter:
  plugin:
    platforms:
      android:
        package: com.corbado.passkeys_doctor
        pluginClass: PasskeysDoctorPlugin
