name: passkeys_example
description: Demonstrates how to use the passkeys plugin.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

resolution: workspace

dependencies:
  corbado_telemetry_api_client: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_localization: ^0.2.1
  flutter_riverpod: ^2.3.10
  go_router: ^10.1.2
  hooks_riverpod: ^2.4.0
  jwt_decoder: ^2.0.1
  overlay_support: ^2.1.0
  passkeys: ^2.22.0
  riverpod: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  patrol: ^4.7.1
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true

patrol:
  app_name: Passkeys Example
  android:
    package_name: com.corbado.passkeys.pub
  ios:
    bundle_id: com.corbado.passkeys.pub
