name: corbado_auth_doctor
description: "Internal debugging tools used to help with Corbado's Flutter SDK."
version: 1.0.0

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  package_info_plus: ^8.3.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  pigeon: ^25.3.1

flutter:
  plugin:
    platforms:
      android:
        package: com.corbado.corbado_auth_doctor
        pluginClass: CorbadoAuthDoctorPlugin
      ios:
        pluginClass: CorbadoAuthDoctorPlugin
