name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.0"

      - name: Set up melos
        uses: bluefireteam/melos-action@v3

      - name: Check formatting
        run: melos run format:check

      - name: Analyze
        run: melos run analyze

      - name: Test
        run: melos run test
